Add Postgres Adapter
utopia-php/database pull request #107
Opened 2022-02-04 15:50 UTC by vermakhushboo

2022-02-06 15:03 UTC, KevinJ-hub commented
Hey @vermakhushboo ,
I have started working on adding postgres adapter a few days back. I had created a [rfc](https://github.com/appwrite/rfc/pull/46) for the same and had a discussion regarding me starting to work on it on appwrites discord server as well.
Are you working on it too?

2022-02-07 15:40 UTC, vermakhushboo commented
> Hey @vermakhushboo , I have started working on adding postgres adapter a few days back. I had created a [rfc](https://github.com/appwrite/rfc/pull/46) for the same and had a discussion regarding me starting to work on it on appwrites discord server as well. Are you working on it too?

Hey @KevinJ-hub, have you made considerable progress on the same? If yes, please take this forward, otherwise, I'd request you to pick something else.

2022-02-07 16:20 UTC, KevinJ-hub commented
> @KevinJ-hub Please create a PR with your changes. The postgres adapter has a high priority at the moment and we want to ensure you have enough time to pick it up. We're expecting to ship it in the coming week. Let us know if you would be able to commit to it slightly_smiling_face

@christyjacob4 Ohhh, I won't be able to commit on finishing it in a week since I am currently a bit caught up with college work. If thats the case then its fine @vermakhushboo you can please continue with postgres adapter I might pick something else and work on it. 👍

2022-02-07 16:36 UTC, christyjacob4 commented
@KevinJ-hub Thank you so much for understanding! Really appreciate the honesty. If you need some guidance on issues you can pick up, please let me know. I'd be happy to assist.

2022-03-26 09:18 UTC, KevinJ-hub commented on src/Database/Adapter/Postgres.php
> +        $write = array_map(fn($role) => '"'.$role.'"', $document->getWrite());
Hey @vermakhushboo,
The double quotes wrapped around role over here are redundent.

2022-03-26 09:18 UTC, KevinJ-hub commented on src/Database/Adapter/Postgres.php
> +        $write = $read = array_map(fn($role) => '"'.$role.'"', $document->getWrite());
The same goes here too.

2022-03-26 10:04 UTC, KevinJ-hub requested changes
Hey @vermakhushboo ,
The double quotes around the role in _read and _write permission seem to be redundent over here since they do not get stored in the postgres DB. So I would like to request you to please check it once and remove them.

2022-03-26 10:04 UTC, KevinJ-hub commented on src/Database/Adapter/Postgres.php
> +        $read = array_map(fn($role) => '"'.$role.'"', $document->getRead());
The double quotes wrapped around role seem to be redundent

2022-03-26 10:04 UTC, KevinJ-hub commented on src/Database/Adapter/Postgres.php
> +        $write = array_map(fn($role) => '"'.$role.'"', $document->getWrite());
Same as above

2022-03-26 10:04 UTC, KevinJ-hub commented on src/Database/Adapter/Postgres.php
> +        $read = array_map(fn($role) => '"'.$role.'"', $document->getRead());
Same as above

2022-03-26 10:04 UTC, KevinJ-hub commented on src/Database/Adapter/Postgres.php
> +        $write = $read = array_map(fn($role) => '"'.$role.'"', $document->getWrite());
Same as above

2022-07-16 17:05 UTC, eldadfux commented
This PR is in an advance stage, and we hope to merge it in a few weeks. Right now we prioritize PRs that address DB reliability and usability before we add major new features.

2023-01-19 09:51 UTC, fogelito commented on src/Database/Adapter/Postgres.php
> +
I think we should  have the lower method for unique index strings something like because of case insensitive?
something like?
if(Database::INDEX_UNIQUE === $type) {
                $attribute = 'lower(' . $attribute . '::text)'; 
}

2023-01-24 11:34 UTC, abnegate reviewed
Looks really good! One small type change and some readability updates and I think we'll be good to go :grin:

2023-01-24 11:34 UTC, abnegate commented on src/Database/Adapter/Postgres.php
> +            ->prepare("CREATE TABLE IF NOT EXISTS \"{$database}\".\"{$namespace}_{$id}\" (
Let's use the `getSQLTable` function here

2023-01-24 11:34 UTC, abnegate commented on src/Database/Adapter/Postgres.php
> +                ->prepare("CREATE TABLE IF NOT EXISTS \"{$database}\".\"{$namespace}_{$id}_perms\" (
Let's use the `getSQLTable` function here

2023-01-24 11:34 UTC, abnegate commented on src/Database/Adapter/Postgres.php
> +                return 'REAL';
Let's use `DOUBLE PRECISION` here

2023-01-24 11:34 UTC, abnegate commented on src/Database/Adapter/Postgres.php
> +        return 'CREATE ' . $type . ' "' . $this->getNamespace() . '_' . $collection . '_' . $id . '" ON "' . $this->getDefaultDatabase() . '"."' . $this->getNamespace() . '_' . $collection . '" ( ' .
Let's use `getSQLTable` here

2023-01-25 23:15 UTC, abnegate approved these changes

2023-01-26 08:18 UTC, fogelito approved these changes

2023-01-26 10:20 UTC, merged