Feat: Disallow failed and pending indexes
utopia-php/database pull request #118
Opened 2022-03-31 10:05 UTC by Meldiron

2022-04-01 11:34 UTC, christyjacob4 commented on src/Database/Validator/OrderAttributes.php
> +            if($index->getAttribute('status') === 'available') {
Only concern is the usage of `available` here 
the status of attributes `processing, available, failed, deleting, stuck` are appwrite specific concepts and we're coupling the library with Appwrite by doing this.

What happens if we decide to change `available` to `ready` in Appwrite. this means we have to release a new library version as well. What about other developers using utopia/database ? Will they be forced to fix their code because we changed a attribute name in Appwrite ? 

So we should find a better way to do this. Defining `status` values as constants can be a good approach. 

Would like a better discussion on this :)

2022-04-01 11:35 UTC, christyjacob4 requested changes
I think this implementation needs more work because of the concern I had.

2022-04-01 14:24 UTC, christyjacob4 commented on src/Database/Validator/OrderAttributes.php
> +            if($index->getAttribute('status') === 'available') {
Another solution is to leave this validator as it is and override it in Appwrite. 
So the Appwrite implementation of OrderAttrbutes can have this specific implementation :)

2022-04-04 13:39 UTC, Meldiron commented
Closing issue. This is appwrite-specific behaviour and should be solved by appwrite-specific validator class (in Appwrite repo)

2022-04-04 13:39 UTC, closed without merging