Feat: Implement updateAttribute()
utopia-php/database pull request #124
Opened 2022-04-07 12:03 UTC by Meldiron

2022-04-07 12:04 UTC, Meldiron commented
Mongo tests are expected to fail, implementation missing.

2022-04-14 13:59 UTC, Meldiron commented
Letting the database natively rebuild index (and decide when it needs to do it) is a better solution because:
- If it fails, the whole thing fails. You don't need to rollback anything
- The index regeneration SHOULD behave the same as CREATE INDEX, so there isn't any advantage or disadvantage

2022-04-17 11:48 UTC, TorstenDittmann requested changes

2022-04-17 11:48 UTC, TorstenDittmann commented on src/Database/Database.php
> +        }, $attributes));
see my other PR reviews regarding this.

2022-04-17 11:48 UTC, TorstenDittmann commented on src/Database/Database.php
> +            $array = $array === null ? $attribute->getAttribute('array') : $array;
```suggestion
            $type ??= $attribute->getAttribute('type');
            $size ??= $attribute->getAttribute('size');
            $signed ??= $attribute->getAttribute('signed');
            $array ??= $attribute->getAttribute('array');
```

2022-04-17 11:48 UTC, TorstenDittmann commented on src/Database/Database.php
> +            $attribute->setAttribute('array', $array);
```suggestion
            $attribute
                ->setAttribute('type', $type)
                ->setAttribute('size', $size)
                ->setAttribute('signed', $signed)
                ->setAttribute('array', $array);
```

this can be chained.

2022-04-17 11:49 UTC, TorstenDittmann commented
Looking at this, it might have been smarter to implement more smaller functions instead of a universal one 🤔

2022-04-19 07:51 UTC, Meldiron commented on src/Database/Database.php
> +        }, $attributes));
Updated. Cant use in_array here, as I need index later on.

2022-04-19 07:51 UTC, Meldiron commented on src/Database/Database.php
> +            $array = $array === null ? $attribute->getAttribute('array') : $array;
Applied

2022-04-19 07:52 UTC, Meldiron commented on src/Database/Database.php
> +            $attribute->setAttribute('array', $array);
Applied

2022-04-19 07:54 UTC, Meldiron commented
> Looking at this, it might have been smarter to implement more smaller functions instead of a universal one 🤔

Yes, there is also an edge case when index rebuild might be triggered, and query results would depend on how strict MariaDB settings are. Before making this user-faced in Appwrite, we need bigger research (what queries cost more) and separate index-rebuilding-logic from the one that doesn't. For now, for migration purposes, this should be quick and simple solution.

Do you want me to work on improving this PR?

2022-04-20 09:47 UTC, TorstenDittmann commented on src/Database/Database.php
> +            $success = $this->adapter->updateAttribute($collection->getId(), $id, $type, $size, $signed, $array);
Don't we want to throw an exception here if something fails?

2022-04-20 09:48 UTC, TorstenDittmann commented on tests/Database/Base.php
> +        ));
For readability we can use named arguments here:
```suggestion
        $this->assertTrue($database->updateAttribute('stocks', 'brand',
            size: 10,
            required: false,
            default: "Unnamed"
        ));
```

2022-04-20 12:33 UTC, Meldiron commented on src/Database/Database.php
> +            $success = $this->adapter->updateAttribute($collection->getId(), $id, $type, $size, $signed, $array);
It will throw automatically, providing a proper message of what happened. For instance `Truncated incorrect INTEGER value: "Matej"`

2022-04-20 13:51 UTC, TorstenDittmann commented on src/Database/Database.php
> +            $success = $this->adapter->updateAttribute($collection->getId(), $id, $type, $size, $signed, $array);
So, why do we need to keep success?

Let's say it returns `false` -> indicating that something went wrong. We are still executing all of its remaining code.

2022-04-20 14:49 UTC, Meldiron commented on src/Database/Database.php
> +            $success = $this->adapter->updateAttribute($collection->getId(), $id, $type, $size, $signed, $array);
Hmm, I see the confusion now. First, I added `return $success` as it was missing.

The boolean comes from `PDO->execute()`. Not sure why it returns a boolean but also throws an exception. Looking at other adapter methods, they all return `execute()`, so they return a boolean.

2022-04-21 09:32 UTC, TorstenDittmann commented on src/Database/Database.php
> +            $success = $this->adapter->updateAttribute($collection->getId(), $id, $type, $size, $signed, $array);
Now we are returning it too early 👍🏻 

The PDO has a configuration, where we can set either throw an exception or return false/true. Let's check if its false here and return false. If not just continue. At the bottom we can just return `true`. That way we make sure, we do actions only when previous steps are successful.

2022-05-15 07:44 UTC, Meldiron commented
Closing PR. Problem addressed in separate PR that makes more developer-friendly interfaces: https://github.com/utopia-php/database/pull/132

Most of the code copied from this PR.

2022-05-15 07:44 UTC, closed without merging