Feat: Queries Gen 2
utopia-php/database pull request #153
Opened 2022-07-15 16:01 UTC by Meldiron

Implementatio of new queries syntax

2022-07-16 16:58 UTC, eldadfux requested changes
Some thoughts:
1. We should try and make the Query class behave closer to our external API for consistency, we can have the same existing constructor with some factory method to represent different methods. 
2. I feel the Query interface can tell a better story. A lot of the new methods could be private, and expose a ,ore intuitive interface, I would love to rethink the structure together.

2022-07-16 16:58 UTC, eldadfux commented on src/Database/Query.php
> +Query::$TYPE_ALIASES = [
This is an anti-pattern. + we can and should treat aliases similar to how we use regular methods to help reduce complexity of this class.

2022-07-16 16:58 UTC, eldadfux commented on src/Database/Validator/QueryValidator.php
> +        if (!in_array($query->getMethod(), $this->operators)) {
If we move from operators to methods we should adapt the terminology library-wide.

2022-07-18 15:09 UTC, stnguyen90 requested changes

2022-07-18 15:09 UTC, stnguyen90 commented on tests/Database/Validator/QueriesTest.php
> +        $query2 = Query::parse('equal("description", "Best movie ever")');
@Meldiron, would you please make sure to have a test for text with a comma to address https://github.com/appwrite/appwrite/issues/3089? Foe example:

```php
 $query = Query::parse('equal("text", ["Contains,Comma", "No Comma"])');
 ```

2022-07-22 13:38 UTC, Meldiron commented
Closing in favour of new branch `2.1`

2022-07-22 13:38 UTC, closed without merging

2022-07-24 05:32 UTC, Meldiron commented on src/Database/Query.php
> +Query::$TYPE_ALIASES = [
We simplified aliases. Tho we can't support the page now, the system is much simpler. We can allow complex aliases in future iterations.

2022-07-24 05:32 UTC, Meldiron commented on tests/Database/Validator/QueriesTest.php
> +        $query2 = Query::parse('equal("description", "Best movie ever")');
Addressed.

2022-07-24 05:35 UTC, Meldiron commented on src/Database/Validator/QueryValidator.php
> +        if (!in_array($query->getMethod(), $this->operators)) {
Adapted. All operators renamed to methods.