Feat: Query gen 2(.1)
utopia-php/database pull request #157
Opened 2022-07-22 13:38 UTC by Meldiron

Previous PR: https://github.com/utopia-php/database/pull/153

2022-07-22 14:06 UTC, TorstenDittmann approved these changes

2022-07-24 07:08 UTC, eldadfux requested changes

2022-07-24 07:08 UTC, eldadfux commented on src/Database/Query.php
> +    public function setFirstParam(string $value): self
The API of the class feels very oriented towards the technical implementation instead of telling the story of the use case for this class and method. I think, `getAttribute`, `getMethod`, and `getValues` would make much more sense and be more intuitive when reading the code.

We could have also introduce static builder methods for this class that would make the API closer to what we have in our Appwrite SDK (not meaning they should be coupled, but they just feel more convenient). For example:
```php
Query::equal(string $attribute, array $values):self;
```

2022-07-24 07:08 UTC, eldadfux commented on tests/Database/Benchmark/QueryBench.php
> +    public function provideAttributes(): Generator
We should properly document this new test and how to run it, alongside other tests related info.

2022-07-24 07:13 UTC, stnguyen90 commented on src/Database/Query.php
> +            $isStringStack = $stringStackState;
Would it be simpler to not use a stack for string?

2022-07-24 07:18 UTC, stnguyen90 commented on src/Database/Query.php
> +                $filter[$i - 1] !== '\\' // Must not be escaped; first cant be
Would this still be able to catch something like: `Query.equal("attr", "\\")`?

2022-07-24 07:42 UTC, Meldiron commented on src/Database/Query.php
> +                    $stack[] = $char;
We don't have support for nested arrays, as they are not required for now. It will be added when it becomes relevant (with array filters).

For now we only support 2 layers - one being params array, one being array value. So for example:

Works: `[ 'equal', ['Matej', 'Eldad'] ]`
Doesn't work: `['equal', [ ['editor','owner'] ] ]`

2022-07-24 07:49 UTC, Meldiron commented on src/Database/Query.php
> +    public function __construct(string $method, array $params)
We removed `operator`. In `equals('name', 'Matej')` all is good, but in a query like `limit(5)` we don't have an operator.

`attribute` was also removed, since that is also not present in `limit(5)`.

We added `method` which replaced `attribute` in the placement of the query. A method is for example `equals`, `limit`, or `offset`.

---

I can see what you mean with a step back. I was thinking about implementing separate interfaces(classes?) for each method. That would give you more high-level of building a query. Would that make sense?

2022-07-24 07:49 UTC, Meldiron commented on src/Database/QueryV1.php
> +class QueryV1
It's for benchmark. @TorstenDittmann  do we want to keep benchmarks as part of PR?

2022-07-24 07:49 UTC, Meldiron commented on tests/Database/Benchmark/QueryBench.php
> +    public function provideAttributes(): Generator
@TorstenDittmann  do we want to keep benchmarks as part of PR?

2022-07-24 07:51 UTC, Meldiron commented on src/Database/Query.php
> +            $isStringStack = $stringStackState;
Not sure if I understand the comment.

We keep a state variable for performance improvement reasons. It simply holds true/false whether the last symbol in the stack array is a string (`"'`).

We need to know if we are in a string stack since `]` inside string should be simply a character in string, but outside of string it ends an array.

We need stack variable since, at the end of anything (for example, end of string), we should still know the previous stack - for example. if we are still in array parameter or not.

2022-07-24 08:02 UTC, Meldiron commented on src/Database/Query.php
> +                $filter[$i - 1] !== '\\' // Must not be escaped; first cant be
Added a new test that passes:
```php
        $query = Query::parse('equal(1, "Hello\\\\World")');
        $this->assertCount(2, $query->getParams());
        $this->assertEquals(1, $query->getParams()[0]);
        $this->assertEquals("Hello\\\\World", $query->getParams()[1]);
```

It's there twice in reality. We need four because of PHP escaping.

2022-07-24 08:05 UTC, Meldiron commented on src/Database/Query.php
> +    public function setFirstParam(string $value): self
I wanted to avoid calling it `getMethod` since you can still call it on `limit(5)` and there you would get `5` as method. Tho, I am opened for suggestions. Should I rename them to original methods?

We can introduce it, yes. That's what I though about in this comment: https://github.com/utopia-php/database/pull/157#discussion_r928212894

> I can see what you mean with a step back. I was thinking about implementing separate interfaces(classes?) for each method. That would give you more high-level of building a query. Would that make sense?

If you give me green, I can go ahead and implement it as static method

2022-07-24 11:36 UTC, stnguyen90 commented on src/Database/Query.php
> +            $isStringStack = $stringStackState;
I was thinking it might be simpler to have $lastQuote that's either ' or " or empty/null instead of using the stack and state variables.

2022-07-24 11:41 UTC, stnguyen90 commented on src/Database/Query.php
> +                $filter[$i - 1] !== '\\' // Must not be escaped; first cant be
I was thinking of this case:

```php
$query = Query::parse('equal(1, "Hello\\\\")');
```

2022-07-24 15:54 UTC, stnguyen90 commented on src/Database/Query.php
> +                $filter[$i - 1] !== '\\' // Must not be escaped; first cant be
Actually, how about this case: 

```php
$query = Query::parse('equal(1, "Hello\\\\", "World")');
```

2022-07-25 08:01 UTC, Meldiron commented on src/Database/Query.php
> +                $filter[$i - 1] !== '\\' // Must not be escaped; first cant be
Good catch with the second test. escaped `\` was still considered escaping symbol in case of the end of the string. Fixed now.

Both tests added and are passing now.

2022-07-25 08:18 UTC, Meldiron commented on src/Database/Query.php
> +            $isStringStack = $stringStackState;
Good point. this is possible because we never have a string inside a string - we don't need a stack. We need stack only because we could (in the future) have an array in an array.

Refactored a little to address this. Changes have no performance impact (or really small).

2022-07-25 11:50 UTC, Meldiron commented on src/Database/QueryV1.php
> +class QueryV1
Removing for now, can be addressed in separate PR in future.

2022-07-25 11:50 UTC, Meldiron commented on tests/Database/Benchmark/QueryBench.php
> +    public function provideAttributes(): Generator
Removing for now, can be addressed in separate PR in future.

2022-07-25 12:55 UTC, eldadfux commented on src/Database/Query.php
> +    public function setFirstParam(string $value): self
I think that with the builder/factory static methods in place we could just set attribute to null, and have proper access methods in place.

2022-07-25 13:03 UTC, TorstenDittmann commented on src/Database/Query.php
> +    public function setFirstParam(string $value): self
We might want to have multiple Query Classes, since they are really hard to mix in combination with Validators.

- The Equal query has stuff like attribute and values (any data type)
- The Limit query has only a single value which is int
- The Offset query has only a single value which is int
- The Order Query has only a single values which are string (maybe even multiple values if we don't want the user to pass multiple orders)
- ...

I am not sure if we can get an interface that makes sense for all. So what about a Base class, extending it for necessary Queries. Otherwise we will have so many conditions for validating everything scattered around the one class for Query and Validator.

2022-07-27 00:02 UTC, stnguyen90 approved these changes
query parsing LGTM

2022-08-14 08:57 UTC, merged