Refactor permissions
utopia-php/database pull request #161
Opened 2022-08-02 07:05 UTC by abnegate

- [BREAKING] Introduce new permissions syntax
- [BREAKING] Remove `$read` attribute from `Document`
- [BREAKING] Remove `$write` attribute from `Document`
- Add `$permissions` array attribute to `Document`
- Add `PERMISSIONS` const array to `Database` to allow extending existing permission types
- Add `getPermissions`, `getPermission($type)`, `getCreate`, `getUpdate` and `getDelete` functions to `Document`
- Add `permissions` and `documentSecurity` parameters to `Adapter` `createCollection` function
- Add `updateCollectionPermissions` and `updateDocumentSecurity` functions to `Database`
- Update `Permissions` validator to handle input of new syntax
- Update tests to support new syntax

2022-08-08 12:16 UTC, TorstenDittmann commented on src/Database/Validator/Permissions.php
> +            \array_shift($matches);
for what do we remove the first value?

2022-08-08 12:16 UTC, TorstenDittmann commented on src/Database/Validator/Permissions.php
> +            $permissionString = '/^(?:' . \implode('|', $this->methods) . ')\(' . $permissionMatcher . '(?:,\s*' . $permissionMatcher . ')*\)$/';
this will probably get more readable if we move logic out of the string building.

something like this:
```suggestion
            $permissions = \implode('|', $this->permissions);
            $methods = \implode('|', $this->methods);
            $permissionMatcher = "((?:{$permissions})(?::(?:[a-z\d]+))?(?:\/(?:[a-z]+))?)";

            // Captures the permissions type (e.g. "read", "update") and ensures at least 1 permission string is provided.
            $permissionString = "/^(?:{$methods})\({$permissionMatcher}(?:,\s*{$permissionMatcher})*\)$/";
```

2022-08-08 12:16 UTC, TorstenDittmann commented on src/Database/Document.php
> +        return [];
we should probably have a unit test for that, so that it will fail if we are missing such method in the future.

2022-08-08 12:16 UTC, TorstenDittmann commented on src/Database/Validator/Permissions.php
> +            $permissionMatcher = '((?:' . \implode('|', $this->permissions) . ')(?::(?:[a-z\d]+))?(?:\/(?:[a-z]+))?)';
we need uppercase and some allowed letters as well right?

```suggestion
            $permissionMatcher = '((?:' . \implode('|', $this->permissions) . ')(?::(?:[a-zA-Z._\-\d]+))?(?:\/(?:[a-zA-Z._\-]+))?)';
```

2022-08-09 00:37 UTC, abnegate commented on src/Database/Validator/Permissions.php
> +            \array_shift($matches);
The first match contains the text that matched the full pattern, we only care that it _did_ match, then we want to shift past that and process the capture groups.

Matches looks like:

```php
array(3) {
  [0]=>
  string(32) "create(user:123abc, team:123abc)"
  [1]=>
  string(11) "user:123abc"
  [2]=>
  string(11) "team:123abc"
}
```

2022-08-10 14:00 UTC, eldadfux requested changes

2022-08-11 06:00 UTC, abnegate commented on src/Database/Validator/Authorization.php
> +        'role:all' => true,
Have added a task for all deprecated components to be removed

2022-08-11 06:13 UTC, abnegate commented on src/Database/Validator/Permissions.php
> +    protected array $statusDimensions = [
They are being verified when used positionally, so:

`users:verified`,
`user:123/verified`,
`status:verified`

would be considered valid, but

`users:invalid`,
`user:123/invalid`,
`status:invalid`

would not. Note that validation depends on the permission type, so a team role in the dimension position is still considered valid e.g.:

`team:123/anythingisvalid`

2022-08-14 06:57 UTC, eldadfux reviewed
All looks good, just waiting for the ID class, and I think we miss tests for the new Role class.

2022-08-14 08:50 UTC, eldadfux reviewed
Some more small comments.

2022-08-14 08:50 UTC, eldadfux commented on src/Database/Document.php
> +                '$id' => ID::custom(true),
```suggestion
                '$id' => true,
```

I think this should stay just true.

2022-08-14 08:50 UTC, eldadfux commented on src/Database/ID.php
> +        return uniqid();
```suggestion
        return 'uniqid()';
```

The custom ID is generated from a different method. We just use the unique function from some tests.

2022-08-14 08:50 UTC, eldadfux commented on src/Database/Permission.php
> +        return $permission->toString();
In the Role and Query classes we just return the object, why do we return a string here?

2022-08-14 08:50 UTC, eldadfux commented on src/Database/Role.php
> +    public static function parse(string $role): Role
Let's always keep static methods at the bottom of the class.

2022-08-14 09:05 UTC, abnegate commented on src/Database/Permission.php
> +        return $permission->toString();
The result is a string here so we can pass it directly to the `$permissions` array

Alternatively, we could call `->toString()` for each permission instead?

2022-08-14 09:55 UTC, eldadfux commented on src/Database/Permission.php
> +        return $permission->toString();
I think this is fine, but I was wondering if we can avoid string internally and just use the object inside the adapters.

2022-08-14 15:22 UTC, merged