Feat query gen 2.3
utopia-php/database pull request #163
Opened 2022-08-09 23:16 UTC by stnguyen90

Dependent on https://github.com/utopia-php/database/pull/162

2022-08-09 23:29 UTC, stnguyen90 commented on src/Database/Adapter/MariaDB.php
> +
Should this be refactored into the base class? Something like:

```php
function processQueries(array $queries = []): array
```

where the array returned will look like:

```php

[
  'filters' => $filters,
  'limit' => $limit,
  'offset' => $offset,
  'orderAttributes' => $orderAttributes,
  'orderTypes' => $orderTypes,
  'cursor' => $cursor,
  'cursorDirection' => $cursorDirection,
]
```

2022-08-10 02:28 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +                    $limit = $values[0];
Let's check for null safety here 
`$values[0] ?? $limit`

2022-08-10 02:28 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +                    $offset = $values[0];
null-safety here as well `$values[0] ?? $offset`

2022-08-10 02:28 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +                    $cursor = $values[0];
`$values[0] ?? $cursor`

2022-08-10 02:33 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +                    $filters[] = $query;
Are all the filters queries simply appended to the list ? Don't they need to be parsed to their SQL forms ?  

```
const TYPE_EQUAL = 'equal';
    const TYPE_NOTEQUAL = 'notEqual';
    const TYPE_LESSER = 'lessThan';
    const TYPE_LESSEREQUAL = 'lessThanEqual';
    const TYPE_GREATER = 'greaterThan';
    const TYPE_GREATEREQUAL = 'greaterThanEqual';
    const TYPE_CONTAINS = 'contains';
    const TYPE_SEARCH = 'search';
```

2022-08-10 03:12 UTC, stnguyen90 commented on src/Database/Adapter/MariaDB.php
> +                    $filters[] = $query;
That's handled later on at https://github.com/utopia-php/database/blob/e48bdaa6ab40b79615673442b5fcdd27f6a4a769/src/Database/Adapter/MariaDB.php#L902

2022-08-10 03:19 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +
We aren't reusing this logic elsewhere right? So I don't think we need to wrap it in a function at this point

2022-08-10 03:20 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +                    $filters[] = $query;
Okay got it 👍  Thanks

2022-08-10 03:21 UTC, stnguyen90 commented on src/Database/Adapter/MariaDB.php
> +
We would probably also use it in the Mongo Adapter 🧐

2022-08-10 03:24 UTC, stnguyen90 commented on src/Database/Adapter/MariaDB.php
> +                    $limit = $values[0];
Good tip!

Also, how and where should we handle if there are multiple limit, offset, or cursor attributes in the queries array?

2022-08-10 15:14 UTC, TorstenDittmann commented on src/Database/Adapter/MariaDB.php
> +                    $filters[] = $query;
Correct me if I am wrong, but shouldn't this whole block be part of the Database Class and not of the Adapter?

The MariaDB Adapter is taking care for SQL stuff and this has nothing todo with it.

I would actually keep the interface of the find method in the adapter as it was before 🤔 otherwise it makes the Adapters more complicated. wdyt @eldadfux ?

2022-08-10 15:17 UTC, TorstenDittmann commented on src/Database/Adapter/MariaDB.php
> +                    $orderTypes[] = $method == Query::TYPE_ORDERASC ? Database::ORDER_ASC : Database::ORDER_DESC;
```suggestion
                    $orderTypes[] = $method === Query::TYPE_ORDERASC ? Database::ORDER_ASC : Database::ORDER_DESC;
```

in PHP I would do a strict equal everytime, otherwise you might get type juggling 👍🏻

2022-08-10 15:28 UTC, TorstenDittmann commented on src/Database/Adapter/MariaDB.php
> +                    $orderTypes[] = $method == Query::TYPE_ORDERASC ? Database::ORDER_ASC : Database::ORDER_DESC;
just as an example if you didn't know:
```php
var_dump("0000" == 0);      // bool(true)
var_dump("0e12345" == "0"); // bool(true)
var_dump("0e34983" == 0);   // bool(true)
```

ref: https://www.php.net/manual/en/language.types.type-juggling.php

2022-08-10 15:45 UTC, stnguyen90 commented on src/Database/Adapter/MariaDB.php
> +                    $filters[] = $query;
> Correct me if I am wrong, but shouldn't this whole block be part of the Database Class and not of the Adapter?

This makes sense to me especially if we're okay with keeping the existing signature for Adapter->find(). @eldadfux ?

2022-08-10 15:48 UTC, stnguyen90 commented on src/Database/Adapter/MariaDB.php
> +
So I'm thinking about moving this to the Queries Validator because I think I'll need this logic in there too:

```php
    /**
     * Iterates through $queries and returns an array with:
     * - filters: array of filter queries
     * - limit: int
     * - offset: int
     * - orderAttributes: array of attribute keys
     * - orderTypes: array of Database::ORDER_ASC or Database::ORDER_DESC
     * - cursor: Document
     * - cursorDirection: Database::CURSOR_BEFORE or Database::CURSOR_AFTER
     * 
     * @param Query[] $queries
     * @param int $defaultLimit
     * @param int $defaultOffset
     * @param string $defaultCursorDirection
     * 
     * @return array
     */
    public static function byMethod(array $queries, int $defaultLimit = 25, int $defaultOffset = 0, string $defaultCursorDirection = Database::CURSOR_AFTER): array
```

and this use it like:

```php
        $queriesByMethod = Queries::byMethod($queries);
        /** @var Query[] */ $filters = $queriesByMethod['filters'];
        /** @var int */ $limit = $queriesByMethod['limit'];
        /** @var int */ $offset = $queriesByMethod['offset'];
        /** @var string[] */ $orderAttributes = $queriesByMethod['orderAttributes'];
        /** @var string[] */ $orderTypes = $queriesByMethod['orderTypes'];
        /** @var Document */ $cursor = $queriesByMethod['cursor'];
        /** @var string[] */ $cursorDirection = $queriesByMethod['cursorDirection'];
```

in Database->find() or Adapter->find().

Thoughts, @christyjacob4 and @TorstenDittmann ?

2022-08-10 15:51 UTC, stnguyen90 commented on src/Database/Adapter/MariaDB.php
> +                    $orderTypes[] = $method == Query::TYPE_ORDERASC ? Database::ORDER_ASC : Database::ORDER_DESC;
Makes sense! Thanks for the tip! 🙏

2022-08-10 17:15 UTC, stnguyen90 commented on src/Database/Adapter/MariaDB.php
> +                    $limit = $values[0];
Updated! I also updated the processing of queries to only factor the 1st limit/offset/cursor encountered.

2022-08-10 17:15 UTC, stnguyen90 commented on src/Database/Adapter/MariaDB.php
> +                    $offset = $values[0];
updated!

2022-08-10 17:17 UTC, stnguyen90 commented on src/Database/Adapter/MariaDB.php
> +                    $cursor = $values[0];
updated!

2022-08-10 17:17 UTC, stnguyen90 commented on src/Database/Adapter/MariaDB.php
> +                    $orderTypes[] = $method == Query::TYPE_ORDERASC ? Database::ORDER_ASC : Database::ORDER_DESC;
updated!

2022-08-10 19:57 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +                    $filters[] = $query;
It might be a good idea to keep the adapter signature as it was and change only the `Database` class signature.

2022-08-11 15:00 UTC, fogelito commented on src/Database/Validator/Queries.php
> +    public function __construct($validator, $attributes, $indexes, $strict = true)
Does it make sense to pass the whole collection? 
instead of $attributes, $indexes

2022-08-11 18:20 UTC, eldadfux commented on src/Database/Validator/Queries.php
> +    public static function byMethod(array $queries, int $defaultLimit = 25, int $defaultOffset = 0, string $defaultCursorDirection = Database::CURSOR_AFTER): array
I don't think this method should handle default values. We should decouple this responsibility. I think we should take care of them when creating the query or in the consuming app (AKA Appwrite).

2022-08-11 18:23 UTC, eldadfux commented on src/Database/Validator/QueryValidator.php
> +    public function __construct(array $attributes, int $maxLimit = 100, int $maxOffset = 5000, int $maxValuesCount = 100)
Out of context, but I don't remember why we call this class `QueryValidator` over `Query`. Can we change it? The namespace is their to indicate this exact scope.

2022-08-11 18:43 UTC, eldadfux commented on src/Database/Validator/QueryValidator.php
>       *
I think we should add a good chunk of docblock to explain the logic we follow.

2022-08-11 18:55 UTC, stnguyen90 commented on src/Database/Database.php
> +        $queriesByMethod = Queries::byMethod($queries);
I'm definitely open to the name, however, I have a couple concerns about doing something like `getMethodByType($type);`

1. we don't really want queries by `Query::TYPE_*`, but more like query type groupings (filters, orders, limit, offset, curors)
2. I wanted to avoid iterating over the $queries array multiple times (ie. `getMethodByType(Query::TYPE_LIMIT)` and `getMethodByType(Query::TYPE_OFFSET)` would iterate over `$queries` twice).
3. I wanted to simplify what `Adapter->find()` needed. For example, given `$queries`, `Adapter->find()` needs `$orderAttributes` AND `$orderTypes`

2022-08-11 19:14 UTC, stnguyen90 commented on src/Database/Validator/QueryValidator.php
>       *
@eldadfux, the logic for if a Query is valid? Should that go in the docblock for `isValid()`?

2022-08-11 19:19 UTC, eldadfux commented on src/Database/Database.php
> +        $queriesByMethod = Queries::byMethod($queries);
We also usually try to keep the return values as close as possible to primitives or arrays of primitives for simplicity.
What about filtering them inside the database instance and saving the results once in a private attribute? That way we can keep the state, simplify the signature, and avoid extra iteration.

2022-08-11 19:25 UTC, eldadfux commented on src/Database/Validator/QueryValidator.php
>       *
Yes.

2022-08-11 19:35 UTC, stnguyen90 commented on src/Database/Database.php
> +        $queriesByMethod = Queries::byMethod($queries);
> What about filtering them inside the database instance and saving the results once in a private attribute? That way we can keep the state, simplify the signature, and avoid extra iteration.

Saving state into the Database instance makes me a little wary in case of any concurrency problems. In addition, this method is needed in the Queries Validator. TBD whether it needs to be used elsewhere in the appwrite repo too.

2022-08-11 19:51 UTC, stnguyen90 commented on src/Database/Validator/Queries.php
> +    public static function byMethod(array $queries, int $defaultLimit = 25, int $defaultOffset = 0, string $defaultCursorDirection = Database::CURSOR_AFTER): array
@eldadfux, the trouble with removing the defaults here is there is a possibility of it being null in `Database->find()`, but we kind of need it for `Adapter->find()`:

```php
        $queriesByMethod = Queries::byMethod($queries);
        /** @var Query[] */ $filters = $queriesByMethod['filters'];
        /** @var int */ $limit = $queriesByMethod['limit'];
        /** @var int */ $offset = $queriesByMethod['offset'];
        /** @var string[] */ $orderAttributes = $queriesByMethod['orderAttributes'];
        /** @var string[] */ $orderTypes = $queriesByMethod['orderTypes'];
        /** @var Document */ $cursor = $queriesByMethod['cursor'];
        /** @var string */ $cursorDirection = $queriesByMethod['cursorDirection'];

        if (!empty($cursor) && $cursor->getCollection() !== $collection->getId()) {
            throw new Exception("cursor Document must be from the same Collection.");
        }

        $cursor = empty($cursor) ? [] : $cursor->getArrayCopy();

        $queries = self::convertQueries($collection, $filters);

        $results = $this->adapter->find(
            $collection->getId(),
            $queries,
            $limit,
            $offset,
            $orderAttributes,
            $orderTypes,
            $cursor,
            $cursorDirection,
        );
```

2022-08-11 19:57 UTC, stnguyen90 commented on src/Database/Validator/Queries.php
> +    public static function byMethod(array $queries, int $defaultLimit = 25, int $defaultOffset = 0, string $defaultCursorDirection = Database::CURSOR_AFTER): array
@eldadfux, unless you think it's okay to pass in null for some of these:

```php
        $results = $this->adapter->find(
            $collection->getId(),
            $queries,
            $limit,
            $offset,
            $orderAttributes,
            $orderTypes,
            $cursor,
            $cursorDirection,
        );
```

even though the default values for `Adapter->find()` won't be used in those cases.

2022-08-11 20:50 UTC, stnguyen90 commented on src/Database/Validator/QueryValidator.php
> +    public function __construct(array $attributes, int $maxLimit = 100, int $maxOffset = 5000, int $maxValuesCount = 100)
renamed!

2022-08-11 20:50 UTC, stnguyen90 commented on src/Database/Validator/QueryValidator.php
>       *
Added docblocks for both Query and Queries!

2022-08-11 20:51 UTC, stnguyen90 commented on src/Database/Validator/Queries.php
> +    public function __construct($validator, $attributes, $indexes, $strict = true)
updated!

2022-08-13 13:47 UTC, eldadfux requested changes
Added a few comments, I think we should be close to a merge :)

2022-08-13 13:47 UTC, eldadfux commented on src/Database/Validator/Queries.php
> +    public static function byMethod(array $queries, int $defaultLimit = 25, int $defaultOffset = 0, string $defaultCursorDirection = Database::CURSOR_AFTER): array
I think we should handle the defaults when calling the adapter->find() method for keeping separation of concerns. Something like:
```php
$results = $this->adapter->find(
    $collection->getId(),
    $queries,
    $limit ?? 25,
    $offset ?? 0,
    ...
 );
```

2022-08-13 13:47 UTC, eldadfux commented on src/Database/Database.php
> +        $queriesByMethod = Queries::byMethod($queries);
As discussed, I think it should be fine concurrency, we can check with @TorstenDittmann later.

2022-08-13 13:47 UTC, eldadfux commented on src/Database/Validator/Queries.php
> +    public static function byMethod(array $queries, int $defaultLimit = 25, int $defaultOffset = 0, string $defaultCursorDirection = Database::CURSOR_AFTER): array
Do we need to take care of the defaults in the validator that uses this method as well?

2022-08-13 13:47 UTC, eldadfux commented on src/Database/Validator/Query.php
> +        if (!$attributeSchema['array'] && $query->getMethod() === DatabaseQuery::TYPE_CONTAINS) {
I don't recall we publicly support this query type.

2022-08-13 13:47 UTC, eldadfux commented on src/Database/Validator/Queries.php
> +     * 2. there is no index with an exact mathc of the order attributes
```suggestion
     * 2. there is no index with an exact match of the order attributes
```

2022-08-13 13:47 UTC, eldadfux commented on src/Database/Validator/Queries.php
>       * Is valid.
A few questions and comments:

- Are we preventing search on attributes with no proper fulltext index?
- We should also allow to limit the type of operators we allow to use. For example, future GEO operators will be disabled when listing users.
- Not sure if passing the collections is the best thing, for listing users, files and more we won't have easy access to it.
- Another problem with this, is that for users, files, etc we won't necessarily allow all attributes in the collections, but a set of very specific and predefined ones.

2022-08-13 13:47 UTC, eldadfux commented on src/Database/Validator/Query.php
> +        if ($method === DatabaseQuery::TYPE_LIMIT) {
I think it will be easier to maintain if we delegate each method check to a different protected method and use a switch case here.

2022-08-13 21:00 UTC, stnguyen90 commented on src/Database/Validator/Query.php
> +        if (!$attributeSchema['array'] && $query->getMethod() === DatabaseQuery::TYPE_CONTAINS) {
We don't. This is leftover from previous implementation: https://github.com/utopia-php/database/blob/0.19.0/src/Database/Validator/QueryValidator.php#L121-L124

2022-08-13 21:11 UTC, stnguyen90 commented on src/Database/Validator/Queries.php
>       * Is valid.
@eldadfux,

> Are we preventing search on attributes with no proper fulltext index?

Yes, here:

https://github.com/utopia-php/database/blob/6dd00dd746395fd992a6a00d7abf96038e280eb8/src/Database/Validator/Queries.php#L136-L140

> We should also allow to limit the type of operators we allow to use. For example, future GEO operators will be disabled when listing users.

Is it okay to tackle that later? Will some sort of index be required for that type of operator? Perhaps we can validate that by checking query method against attribute type? 

> Not sure if passing the collections is the best thing, for listing users, files and more we won't have easy access to it.
Another problem with this, is that for users, files, etc we won't necessarily allow all attributes in the collections, but a set of very specific and predefined ones.

I'll change this back to take attributes and indexes.

> Another problem with this, is that for users, files, etc we won't necessarily allow all attributes in the collections, but a set of very specific and predefined ones.

If I change back to $attributes, we can pass in a set of attributes into the validator.

2022-08-13 22:27 UTC, stnguyen90 commented on src/Database/Database.php
> +        $queriesByMethod = Queries::byMethod($queries);
In addition, this method is needed in the Queries Validator.

2022-08-13 22:28 UTC, stnguyen90 commented on src/Database/Validator/Queries.php
> +    public static function byMethod(array $queries, int $defaultLimit = 25, int $defaultOffset = 0, string $defaultCursorDirection = Database::CURSOR_AFTER): array
I have removed default values and hardcoded the defaults in `Database->find()`

2022-08-14 06:17 UTC, eldadfux commented on src/Database/Validator/Queries.php
>       * Is valid.
> Is it okay to tackle that later? Will some sort of index be required for that type of operator? Perhaps we can validate that by checking query method against attribute type?

Might be OK, I'll let you know if I think of a problem.

> If I change back to $attributes, we can pass in a set of attributes into the validator.

Are we passing only array of attributes names or array of attribute objects?

2022-08-14 06:17 UTC, eldadfux commented on src/Database/Validator/Queries.php
> +    public static function byMethod(array $queries): array
Maybe the name `group` or `groupByType` will better explain this logic now.

2022-08-14 06:18 UTC, eldadfux commented on src/Database/Validator/Query.php
> +        if (!$attributeSchema['array'] && $query->getMethod() === DatabaseQuery::TYPE_CONTAINS) {
Should we remove it? It might be confusing to other team members, are we even using this anywhere?

2022-08-14 06:29 UTC, stnguyen90 commented on src/Database/Validator/Query.php
> +        if (!$attributeSchema['array'] && $query->getMethod() === DatabaseQuery::TYPE_CONTAINS) {
I think it's fine to keep as progress in adding support for it. The only thing left is adding support in the Adapter layer. 

If you want me to remove it, I can, but would you want to remove everything about it in Utopia\Database\Query?

2022-08-14 06:30 UTC, stnguyen90 commented on src/Database/Validator/Queries.php
>       * Is valid.
Attribute Documents because OrderAttributes Validator required Attribute Documents.

2022-08-14 06:31 UTC, stnguyen90 commented on src/Database/Validator/Queries.php
> +    public static function byMethod(array $queries): array
👍 I'll rename to `groupByType()`

2022-08-14 07:04 UTC, eldadfux commented on src/Database/Validator/Query.php
> +        if (!$attributeSchema['array'] && $query->getMethod() === DatabaseQuery::TYPE_CONTAINS) {
No worries, let's tackle it later.

2022-08-14 07:06 UTC, eldadfux commented on src/Database/Validator/Queries.php
>       * Is valid.
We might need to extend this validator in Appwrite so we don't need to work hard to mock these attributes inside the controllers.

2022-08-14 08:53 UTC, eldadfux approved these changes

2022-08-14 08:57 UTC, merged