Datetime tz filter
utopia-php/database pull request #166
Opened 2022-08-15 14:18 UTC by christyjacob4

2022-08-15 14:26 UTC, eldadfux approved these changes

2022-08-15 14:26 UTC, eldadfux commented on src/Database/Database.php
>               * @return string|null
What is the default `date_default_timezone_get` for our server?

2022-08-15 15:13 UTC, stnguyen90 commented on src/Database/Database.php
>               * @return string|null
From my experience, the appwrite docker images have the timezone set to UTC:

```shell
$ docker run appwrite/appwrite php -r 'print date_default_timezone_get() . "\n";'
UTC
```

2022-08-15 15:16 UTC, fogelito commented on src/Database/Database.php
>               * @return string|null
$app = new App('UTC');

2022-08-15 15:29 UTC, stnguyen90 commented on tests/Database/Validator/DateTimeTest.php
> +        $this->assertEquals("2022-12-04T09:31:52.681+00:00", DateTime::formatTz("2022-12-04 09:31:52.681"));
I can confirm Dart and Javascript can parse this easily:

Dart: 

```dart
final nz = DateTime.parse("2022-12-04T09:31:52.681+00:00");
print(nz.toIso8601String()); // 2022-12-04T09:31:52.681Z
```

Javascript:

```javascript
d = new Date("2022-12-04T09:31:52.681+00:00");
console.log(d.toISOString()); // 2022-12-04T09:31:52.681Z
```

2022-08-15 15:51 UTC, stnguyen90 approved these changes
It would be nice to have an additional test case, but not a blocker.

2022-08-15 15:51 UTC, stnguyen90 commented on src/Database/DateTime.php
> +            return $dbFormat;
Can we get a test case for this?

2022-08-15 15:51 UTC, stnguyen90 commented on src/Database/DateTime.php
> +    protected static string $formatDb = 'Y-m-d H:i:s.v';
This is probably okay for now, but we may want to figure out a way to handle this for different databases.

2022-08-15 16:11 UTC, fogelito commented on tests/Database/Validator/DateTimeTest.php
> +        $this->assertEquals("2022-12-04T09:31:52.681+00:00", DateTime::formatTz("2022-12-04 09:31:52.681"));
Thanks a lot

2022-08-15 16:12 UTC, fogelito commented on src/Database/DateTime.php
> +            return $dbFormat;
There is one assertion test, most will be on Appwrite , since the filter happen there

2022-08-15 16:12 UTC, fogelito commented on src/Database/DateTime.php
> +    protected static string $formatDb = 'Y-m-d H:i:s.v';
I agree

2022-08-16 18:08 UTC, eldadfux requested changes

2022-08-16 18:08 UTC, eldadfux commented on src/Database/Database.php
> +    public function getInternalAttributes(): array
I think the more common way would be to just have a protected property named `attributes`, no need for a method. Definitely not a public one. When we do decide to add a public method, it should have tests.

2022-08-16 18:11 UTC, fogelito commented on src/Database/DateTime.php
> +    protected static string $formatDb = 'Y-m-d H:i:s.v';
OK!

2022-08-16 18:11 UTC, christyjacob4 commented on src/Database/Database.php
> +            )
Since we have 4 internal attributes, its better to keep all of them consistent and include the remaining in this array as well. 

`$id` and `$collection`

Please refer 
https://github.com/utopia-php/database/blob/479b4b0f84417253c4f749d731773b27c980b800/src/Database/Database.php#L1175-L1178

2022-08-16 18:13 UTC, christyjacob4 commented on tests/Database/Base.php
> +        $this->assertEquals('1975-06-12T13:12:55.000+00:00', $result->getAttribute('registration'));
Can we add more assertions to check the values of `$createdAt` and `$updatedAt` attributes ?

2022-08-16 19:06 UTC, fogelito commented on src/Database/Database.php
> +    public function getInternalAttributes(): array
I added:
protected array $attributes
I need the function still for to convert to list of Documents

2022-08-16 19:07 UTC, fogelito commented on src/Database/Database.php
> +            )
Sure! 
create : 
protected array $internals ....

2022-08-16 19:56 UTC, christyjacob4 reviewed
Looks good 👍

2022-08-16 19:57 UTC, christyjacob4 commented on src/Database/Database.php
> +
```suggestion
```
My OCD wants to remove this line

2022-08-16 19:57 UTC, eldadfux commented on src/Database/Database.php
> +
```suggestion
```

2022-08-16 19:57 UTC, eldadfux commented on src/Database/Database.php
> +                } catch (Throwable $th) {
```suggestion
                } catch (\Throwable $th) {
```

2022-08-16 19:57 UTC, eldadfux commented on src/Database/Database.php
> +    public function getInternalAttributes(): array
php 8 don't allow us to set them in the protected attribute? 😒

2022-08-17 09:01 UTC, christyjacob4 commented on src/Database/Database.php
> +    public function getInternalAttributes(): array
not really :(

2022-08-17 09:02 UTC, christyjacob4 commented on src/Database/Database.php
> -            throw $th;
why did we remove try catch ?

2022-08-17 12:53 UTC, eldadfux commented on src/Database/Database.php
> +    public function getInternalAttributes(): array
Bummer.

2022-08-17 12:54 UTC, eldadfux approved these changes

2022-08-17 12:55 UTC, merged