Refactor permissions
utopia-php/database pull request #172
Opened 2022-08-25 08:49 UTC by abnegate

- Revert permissions checks to check document level
- **Remove authorisation check for document create**
- Implement aggregate functionality permission helper

We have verified that the removal of the authorisation check in `createDocument` should not have an impact in Appwrite, as all resource types that are publicly creatable, already have the necessary checks in place to ensure they can not be abused.

2022-08-25 18:49 UTC, christyjacob4 approved these changes
Looks good 👍

2022-08-26 08:37 UTC, Meldiron requested changes

2022-08-26 08:37 UTC, Meldiron commented on tests/Database/Base.php
> -        Authorization::cleanRoles();
Why did we re,oveclearRoles from the top? Are we expecting to get roles from a different test? Sounds scarry.
Could we clear roles  here at the top and set roles we need? For example `any` or `user:1` or whatever we need.

2022-08-26 08:37 UTC, Meldiron commented on tests/Database/Base.php
> -        Authorization::cleanRoles();
Same as above, why did we remove this? Can we keep it? Should work the same, as creation should be allowed to everyone.

2022-08-26 08:37 UTC, Meldiron commented on src/Database/Permission.php
> +                unset($permissions[$i]);
I can imagine this to be hard to maintain with new changes (pushing and unsetting). Can we separate it? Use $permissions as read-only input, and have a new array for aggregated stuff.

2022-08-26 08:37 UTC, Meldiron commented on src/Database/Permission.php
> +    ];
Just a question, does this mean that `write` permission is supported? So I can do `createDocument(Permissions.write('any'))` and it would give create+update+delete permissions?

If so, can we have one more for `admin` that would allow everything? (read+write)

2022-08-26 09:05 UTC, abnegate commented on src/Database/Permission.php
> +    ];
Correct, you can use write with SDK's or the API. Admin will be implemented in a future release

2022-08-26 09:07 UTC, Meldiron approved these changes

2022-08-27 09:16 UTC, merged

2023-04-17 22:52 UTC, stnguyen90 commented
Closes: https://github.com/appwrite/appwrite/issues/4543