Added SQLite adapter
utopia-php/database pull request #187
Opened 2022-09-16 21:56 UTC by eldadfux

2022-09-18 15:56 UTC, fogelito commented on src/Database/Adapter/Mongo/MongoDBAdapter.php
> +        return 0;
This will have to check , perhaps a big number?

2022-09-18 16:02 UTC, fogelito commented on src/Database/Database.php
> +    const METADATA = 'metadata';
Remember to migrate Appwrite Collections

2022-09-18 16:07 UTC, fogelito commented on src/Database/Database.php
>          ]);
Perhaps we can use my pr of creating the attributes and indexes 1 by 1 not by schema?
https://github.com/utopia-php/database/pull/188

2022-09-19 19:14 UTC, wess approved these changes

2022-09-20 09:02 UTC, abnegate commented on tests/Database/Base.php
> +            $this->assertEquals(false, $schemaSupport); // Dummy assertion to skip test
```suggestion
            $this->markTestSkipped()
```

2022-09-20 09:03 UTC, abnegate commented on tests/Database/Base.php
> +            $this->assertEquals(false, $fulltextSupport); // dummy assertion to skip this test
```suggestion
            $this->markTestSkipped()
```

2022-09-20 10:55 UTC, wess requested changes
Failing test. with testFind for sqlite. Mongo is passing, and syntax looks good.

2022-09-24 06:55 UTC, eldadfux commented on src/Database/Adapter/Mongo/MongoDBAdapter.php
> +        return 0;
Mongo has not limit, we use 0 for unlimited, this is documented in the abstract class. Not new to this PR, I just changed the method name.

2022-09-24 06:56 UTC, eldadfux commented on src/Database/Database.php
> +    const METADATA = 'metadata';
Listed in the PR comments. Thanks

2022-09-24 06:56 UTC, eldadfux commented on src/Database/Database.php
>          ]);
We can discuss this separately to avoid blocking this PR.

2022-09-24 06:58 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +                ->prepare("DROP TABLE IF EXISTS {$this->getSQLSchema()}`{$this->getNamespace()}_{$id}`, {$this->getSQLSchema()}`{$this->getNamespace()}_{$id}_perms`;")
Yes, this sounds better!

2022-09-24 14:24 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +                ->prepare("DROP TABLE IF EXISTS {$this->getSQLSchema()}`{$this->getNamespace()}_{$id}`, {$this->getSQLSchema()}`{$this->getNamespace()}_{$id}_perms`;")
Done and resolved.

2022-09-27 19:30 UTC, merged