Attributes indexes 1 by 1
utopia-php/database pull request #188
Opened 2022-09-18 16:04 UTC by fogelito

This PR on createCollection will create the attributes and indexes 1 by 1 not by schema.

2022-09-20 13:00 UTC, TorstenDittmann requested changes

2022-09-20 13:00 UTC, TorstenDittmann commented on src/Database/Database.php
> +use function PHPUnit\Framework\throwException;
unused import?

2022-09-20 13:00 UTC, TorstenDittmann commented on src/Database/Database.php
> +        $collection->setAttribute('indexes', $indexes);
```suggestion
        $collection
            ->setAttribute('attributes', $attributes);
            ->setAttribute('indexes', $indexes);
```

2022-09-20 13:00 UTC, TorstenDittmann commented on src/Database/Database.php
> +            self::createAttribute(
```suggestion
            $this->createAttribute(
```

2022-09-20 13:00 UTC, TorstenDittmann commented on src/Database/Database.php
> +                $attribute->getAttribute('formatOptions')?? [],
```suggestion
                $attribute->getAttribute('formatOptions') ?? [],
```

2022-09-20 13:00 UTC, TorstenDittmann commented on src/Database/Database.php
> +            self::createIndex(
```suggestion
            $this->createIndex(
```

2022-09-20 13:00 UTC, TorstenDittmann commented on src/Database/Database.php
> +    public function createCollectionIndexes(string $collection, array $indexes = []): bool
```suggestion
    public function createIndexes(string $collection, array $indexes = []): bool
```

2022-09-20 13:00 UTC, TorstenDittmann commented on src/Database/Database.php
> +    public function createCollectionAttributes(string $collection, array $attributes = []): bool
```suggestion
    public function createAttributes(string $collection, array $attributes = []): bool
```

2022-09-20 13:00 UTC, TorstenDittmann commented on src/Database/Database.php
> +            throw new Exception('CreateAttribute error empty collection');
```suggestion
            throw new Exception("Collection can't be empty.");
```

2022-09-20 13:00 UTC, TorstenDittmann commented on src/Database/Database.php
> +            throw new Exception('CreateAttribute error empty id');
```suggestion
            throw new Exception("ID can't be empty");
```

2022-09-20 13:00 UTC, TorstenDittmann commented on src/Database/Database.php
> +            if (\strtolower($attribute->getId()) === \strtolower($id) && $collection->getId() != '_metadata') {
```suggestion
            if (\strtolower($attribute->getId()) === \strtolower($id) && $collection->getId() !== self::METADATA) {
```

2022-09-20 13:42 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +        ->execute();
OK

2022-09-20 13:43 UTC, fogelito commented on src/Database/Database.php
> +use function PHPUnit\Framework\throwException;
REMOVED

2022-09-20 13:46 UTC, fogelito commented on src/Database/Database.php
> +        $collection->setAttribute('indexes', $indexes);
CHANGED

2022-10-25 06:43 UTC, eldadfux commented
We decided to not continue with this route due to performance issues. Creating an index one by one turned out to be significantly slower.

2022-10-25 06:43 UTC, closed without merging