add event, triggers and listeners support
utopia-php/database pull request #201
Opened 2022-10-12 08:37 UTC by lohanidamodar

2022-10-12 08:47 UTC, eldadfux requested changes

2022-10-12 08:47 UTC, eldadfux commented on src/Database/Database.php
> +    const EVENT_CREATE_DATABASE = 'create_database';
```suggestion
    const EVENT_DATABASE_CREATE = 'database_create';
```

Makes more sense to have the namespace before the action

2022-10-12 08:47 UTC, eldadfux commented on src/Database/Database.php
> +        foreach ($this->listeners['*'] as $callback) {
```suggestion
        foreach ($this->listeners['*'] as $callback) {
```

We can have a constant for all events as well

2022-10-12 08:47 UTC, eldadfux commented on src/Database/Database.php
> +        $this->trigger(self::EVENT_DELETE_COLLECTION, ['id' => $id, 'deleted' => $deleted]);
Can we be more consistent with the payload we're passing? deleted can be just named as document or data? Do we need to specifically pass `id` and `collections`? Don't we already have them in the deleted/created/updated document/collection/database

2022-10-12 08:51 UTC, lohanidamodar commented on src/Database/Database.php
> +        foreach ($this->listeners['*'] as $callback) {
updated

2022-10-12 09:52 UTC, eldadfux reviewed
All looks good, I would add some unit tests to check all events are executed.

2022-10-16 06:14 UTC, eldadfux commented on src/Database/Database.php
> +    public function silent(callable $callback) {
Let's add a docblock (I know...), can we also have a return type?

2022-10-16 06:14 UTC, eldadfux commented on tests/Database/Base.php
> +    {
Does this tests validate all events have actually been triggered? Can we know if an event was triggered more than once? It will be important to make sure no future maintainers forget to silent internal calls.

2022-10-16 06:15 UTC, lohanidamodar commented on tests/Database/Base.php
> +    {
Yes this test does validate events actually been triggered and this test will fail if event was triggered more than once

2022-10-16 06:16 UTC, lohanidamodar commented on src/Database/Database.php
> +    public function silent(callable $callback) {
Return type will depend on the callback as it returns whatever the callback returns so? Auth::skip doesn't have one as well? Can we add mixed?

2022-10-16 06:19 UTC, eldadfux commented on src/Database/Database.php
> +    public function silent(callable $callback) {
Not sure from which version mixed is supported, please check.

2022-10-16 07:39 UTC, eldadfux approved these changes

2022-10-16 07:39 UTC, merged