long size varchar with long index size mysql
utopia-php/database pull request #210
Opened 2022-10-20 19:39 UTC by fogelito

2022-10-21 06:00 UTC, eldadfux requested changes
There are a lot of leftovers, not sure if the PR is ready or not, but left some comments.

2022-10-21 06:00 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +        $collectionAttributes = [];
Not sure what this variable name should indicate. The story of this new logic is not very clear.

2022-10-23 15:18 UTC, fogelito commented on src/Database/Database.php
> +            throw new Exception('Not found');
Changed to 
throw new Exception('Collection ' .$collectionName . ' Not found');
I added In a few more places we are called the collection object.

2022-10-23 15:18 UTC, fogelito commented on src/Database/Database.php
> +            throw new Exception('Not found');
ok. I added some more checks like this where the collection was called.

2022-10-23 15:19 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +        $collectionAttributes = [];
I changed it for functions I think it is much clear now.

2022-10-23 15:27 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +//            $size = (int)($lengths[$key] ?? 0);
This is the Index size, not the attribute size, it is not mandatory.
I commend out this part since I have questions. This is another place we have to fix regardless of the current bug.

2022-10-24 07:20 UTC, TorstenDittmann requested changes

2022-10-24 07:20 UTC, TorstenDittmann commented on src/Database/Adapter.php
> +    }
I don't think this needs to be public, protected maybe.

I see we only use it once and only in a single adapter - not sure if its worth its own method 🤔

2022-10-24 15:48 UTC, fogelito commented on src/Database/Adapter.php
> +    }
I changed it to protected, 
I remember some logic of finding an attribute in a list in the compound index perhaps

2022-10-25 06:03 UTC, eldadfux requested changes

2022-10-25 06:03 UTC, eldadfux commented on src/Database/Adapter.php
> +    public function fixIndex(Document $index, array $attributes): Document {
This shouldn't be part of the adapter interface as this issue is specific to MariaDB/MySQL.

Also, the name suggest this is a bug fix and might encourage future maintainer to use this as a generic place for adding patches that will increase technical debt.

This method should be designed for enforcing the required behavior for the relevant adapter. `getSQLIndexLimit(int $length): int` might better explain what we do, and work better with the existing patterns of `getSQLIndex()` and `getSQLIndexType()`. Very important we keep consistency and predictability across the library.

2022-10-25 07:03 UTC, fogelito commented on src/Database/Database.php
> +    public function sum(string $collectionName, string $attribute, array $queries = [], int $max = 0)
If the collection is empty will it return the name? I need to check

2022-10-26 07:15 UTC, fogelito commented on src/Database/Database.php
> +    public function sum(string $collectionName, string $attribute, array $queries = [], int $max = 0)
if $collection->isEmpty() 
$collection->getId() is empty as well
throw new Exception('Collection ' .$collection->getId() . ' Not found');

2022-10-26 07:17 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +        foreach ($attributes as $attribute) {
ok

2022-10-26 09:48 UTC, fogelito commented on src/Database/Adapter.php
> +    public function fixIndex(Document $index, array $attributes): Document {
I Do not think this is relevant since now it moved to the MariaDB.
Please give me a better name for fixIndex
This function returns the index after checking and overwriting bad values

2023-06-11 06:26 UTC, fogelito commented
Yes, I will close this one.
Was taken care by a validation here:
#271

2023-06-11 06:26 UTC, closed without merging