increase Document Attribute
utopia-php/database pull request #217
Opened 2022-10-31 18:52 UTC by fogelito

2022-10-31 19:27 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +        $stmt->execute() || throw new Exception('Failed to update Attribute');
Let's return a boolean here as well and also update the signature.

2022-10-31 19:27 UTC, eldadfux commented on src/Database/Database.php
> +    const EVENT_DOCUMENT_DECREMENT = 'document_DECREMENT';
```suggestion
    const EVENT_DOCUMENT_DECREMENT = 'document_decrement';
```

2022-10-31 19:27 UTC, eldadfux commented on src/Database/Database.php
> +        if($collection->isEmpty()){
```suggestion

        if($collection->isEmpty()){
```

2022-10-31 19:27 UTC, eldadfux commented on src/Database/Database.php
> +        $this->adapter->increaseDocumentAttribute($collection->getId(), $id, $attribute, $value, null, $max);
We can check for success here and return the correct result at the end.

2022-10-31 19:27 UTC, eldadfux commented on src/Database/Database.php
> +            throw new Exception('Attribute value Exceeds maximum limit ' . $max);
```suggestion
            throw new Exception('Attribute value exceeds maximum limit: ' . $max);
```

2022-10-31 19:27 UTC, eldadfux commented on src/Database/Database.php
> +        if (!in_array($attribute, \array_map(fn($a) => $a['$id'], $collection->getAttribute('attributes', [])))) {
I think we can have a faster check by doing the validation against the document instead of the collection.

2022-11-01 16:25 UTC, christyjacob4 commented on composer.json
> +        "utopia-php/cache": "0.7.*",
Let's update the cache library to use `0.8.0`
We can even move the `cache` dependency to  the `require-dev` section i suppose 🤔

2022-11-01 16:26 UTC, christyjacob4 commented on phpunit.xml
> +    stopOnFailure="true">
reminder to revert it back

2022-11-01 16:34 UTC, christyjacob4 commented on src/Database/Adapter.php
> +    abstract function increaseDocumentAttribute(string $collection, string $id, string $attribute, int $value, int $min = null, int $max = null);
```suggestion
    abstract function increaseDocumentAttribute(string $collection, string $id, string $attribute, int $value, ?int $min = null, ?int $max = null);
```

2022-11-01 16:36 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +     * @return void
We're missing the `$min` parameter

2022-11-01 16:36 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +    public function increaseDocumentAttribute(string $collection, string $id, string $attribute, int $value, int $min = null, int $max = null)
```suggestion
    public function increaseDocumentAttribute(string $collection, string $id, string $attribute, int $value, ?int $min = null, ?int $max = null): void
```

2022-11-02 09:39 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +        $stmt->execute() || throw new Exception('Failed to update Attribute');
ok

2022-11-02 10:12 UTC, fogelito commented on src/Database/Database.php
> +        $this->adapter->increaseDocumentAttribute($collection->getId(), $id, $attribute, $value, null, $max);
Done

2022-11-02 10:17 UTC, fogelito commented on src/Database/Database.php
> +        if (!in_array($attribute, \array_map(fn($a) => $a['$id'], $collection->getAttribute('attributes', [])))) {
This check will be changes a little since I need the attribute any how for checking the wether it is an int or float

2022-11-02 11:43 UTC, fogelito commented on composer.json
> +        "utopia-php/cache": "0.7.*",
Done

2022-11-02 11:45 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +     * @return void
done!

2022-11-02 16:07 UTC, eldadfux requested changes

2022-11-02 16:07 UTC, eldadfux commented on composer.json
> +        "utopia-php/cache": "0.8.*"
Why have we moved Utopia/Cache to be a dev dependency?

2022-11-02 16:07 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +use phpDocumentor\Reflection\DocBlock\Tags\Reference\Url;
This is a mistake.

2022-11-02 16:07 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +
```suggestion
```

Extra space

2022-11-02 16:07 UTC, eldadfux commented on src/Database/Adapter/Mongo/MongoDBAdapter.php
> +
```suggestion
```

Extra space

2022-11-02 16:07 UTC, eldadfux commented on src/Database/Database.php
> +use Utopia\Database\Exception\Duplicate as DuplicateException;
This is a mistake, we're using the same exception twice. Would also be better to group all exceptions here one after the other.

2022-11-02 16:07 UTC, eldadfux commented on tests/Database/Base.php
> +
```suggestion
```

Extra space

2022-11-02 16:07 UTC, eldadfux commented on tests/Database/Base.php
>      }
We should also update the events tests to test against the newly added events

2022-11-02 16:12 UTC, fogelito commented on composer.json
> +        "utopia-php/cache": "0.8.*"
@christyjacob4 asked for this

2022-11-02 16:15 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +use phpDocumentor\Reflection\DocBlock\Tags\Reference\Url;
done

2022-11-02 16:16 UTC, fogelito commented on phpunit.xml
> +    stopOnFailure="true">
done

2022-11-02 16:24 UTC, fogelito commented on src/Database/Database.php
> +use Utopia\Database\Exception\Duplicate as DuplicateException;
Done

2022-11-02 17:08 UTC, TorstenDittmann commented on src/Database/Adapter/MariaDB.php
> +    public function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value, int $min = null, int $max = null): bool
We should not return `bool`, but return the actual value back after incrementing.

2022-11-03 00:48 UTC, abnegate requested changes

2022-11-03 00:48 UTC, abnegate commented on src/Database/Adapter.php
> +    abstract function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value, int $min = null, int $max = null):bool;
Should min/max allow `float` as well?

2022-11-03 00:48 UTC, abnegate commented on src/Database/Database.php
> +        if($value < 1 || !is_numeric($value)){
The `is_numeric` check is not necessary here; passing anything other than int or float will throw an error

2022-11-03 00:48 UTC, abnegate commented on src/Database/Database.php
> +        if($value < 1 || !is_numeric($value)){
The `is_numeric` check is not necessary here; passing anything other than int or float will throw an error

2022-11-03 00:48 UTC, abnegate commented on tests/Database/Base.php
> +        $this->assertEquals(false, static::getDatabase()->increaseDocumentAttribute('increase_decrease', $document->getId(), 'increase', 1, 102));
Let's add a float check here

2022-11-03 00:48 UTC, abnegate commented on tests/Database/Base.php
> +        $this->assertEquals(false, static::getDatabase()->decreaseDocumentAttribute('increase_decrease', $document->getId(), 'decrease', 1, 98));
Let's add a float check here

2022-11-03 06:09 UTC, christyjacob4 commented on composer.json
> +        "utopia-php/cache": "0.8.*"
@fogelito My bad. I thought we used it only for tests. Looks like we do use it inside the DB adapter.

2022-11-03 06:09 UTC, christyjacob4 commented on composer.json
> +        "utopia-php/cache": "0.8.*"
You can revert it back 👍

2022-11-03 06:12 UTC, christyjacob4 commented on src/Database/Adapter.php
> +    abstract function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value, int $min = null, int $max = null):bool;
```suggestion
    abstract function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value, ?int $min = null, ?int $max = null):bool;
```

If min and max are nullable shouldn't they be like this ?

2022-11-03 06:13 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +    public function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value, int $min = null, int $max = null): bool
```suggestion
    public function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value, ?int $min = null, ?int $max = null): bool
```

2022-11-03 06:14 UTC, christyjacob4 commented on src/Database/Adapter/Mongo/MongoDBAdapter.php
> +    function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value, int $min = null, int $max = null):bool {
```suggestion
    function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value, ?int $min = null, ?int $max = null):bool {
```

2022-11-03 06:15 UTC, christyjacob4 commented on src/Database/Database.php
> +     * @param null $max
```suggestion
     * @param int|null $max
```

2022-11-03 06:16 UTC, christyjacob4 commented on src/Database/Database.php
> +     * @param null $max
What is the expected datatype of `$max` ?

2022-11-03 06:16 UTC, christyjacob4 commented on src/Database/Database.php
> +    public function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value = 1, $max = null): bool
```suggestion
    public function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value = 1, ?int $max = null): bool
```

shouldn't max be a nullable int ?

2022-11-03 06:17 UTC, christyjacob4 commented on src/Database/Database.php
> +     * @param null $min
```suggestion
     * @param int | null $min
```

2022-11-03 06:17 UTC, christyjacob4 commented on src/Database/Database.php
> +    public function decreaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value = 1, $min = null): bool
```suggestion
    public function decreaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value = 1, ?int $min = null): bool
```

2022-11-03 08:05 UTC, fogelito commented on composer.json
> +        "utopia-php/cache": "0.8.*"
Done!

2022-11-03 08:09 UTC, fogelito commented on tests/Database/Base.php
>      }
There is an event for deleteCollection.
I added tests events for 
Database::EVENT_DOCUMENT_INCREASE,
Database::EVENT_DOCUMENT_DECREASE,

2022-11-03 08:13 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +        $stmt->bindValue(':val', $value, PDO::PARAM_INT);
Yes it is ok :)

2022-11-03 08:18 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +    public function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value, int $min = null, int $max = null): bool
Can we think about an implementation? since I will have to make an extra query for this?
I am not sure we can use the document value fetched + $value added because of race conditions?

2022-11-03 08:48 UTC, eldadfux commented on composer.json
> +        "utopia-php/cache": "0.7.*",
We just need to upgrade the version. Cache is a required dependency.

2022-11-03 08:48 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +     * @return void
@fogelito have you committed your changes?

2022-11-03 08:48 UTC, eldadfux commented on composer.json
>          "utopia-php/cache": "0.8.*"
```suggestion
        "php": ">=8.0",
        "utopia-php/cache": "0.8.*",
        "utopia-php/framework": "0.*.*",
        "ext-pdo": "*"
```

Let's keep the list organized.

2022-11-03 08:48 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +    public function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value, int $min = null, int $max = null): bool
@TorstenDittmann for simplicity I would skip it for now.

2022-11-03 08:48 UTC, eldadfux commented on tests/Database/Adapter/MongoDBTest.php
> +//
Reminder to bring this back.

2022-11-03 08:56 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +    public function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value, int $min = null, int $max = null): bool
done

2022-11-03 10:24 UTC, fogelito commented on tests/Database/Base.php
> +
done!

2022-11-03 10:34 UTC, fogelito commented on tests/Database/Base.php
> +
I Can not, we do not return a value after the update only true on success.
@eldadfux

2022-11-03 10:50 UTC, fogelito commented on src/Database/Adapter.php
> +    abstract function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value, int $min = null, int $max = null):bool;
yes done! I tested as well

2022-11-03 10:54 UTC, fogelito commented on src/Database/Database.php
> +        if($value < 1 || !is_numeric($value)){
That's nice tries to pass as "2" value, PHP cast it to int.
removed

2022-11-03 10:55 UTC, fogelito commented on src/Database/Database.php
> +        if($value < 1 || !is_numeric($value)){
removed

2022-11-03 11:14 UTC, fogelito commented on tests/Database/Base.php
> +        $this->assertEquals(false, static::getDatabase()->decreaseDocumentAttribute('increase_decrease', $document->getId(), 'decrease', 1, 98));
done!

2022-11-03 11:15 UTC, fogelito commented on src/Database/Database.php
> +    public function increaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value = 1, $max = null): bool
yes and added a float option as well

2022-11-03 11:15 UTC, fogelito commented on src/Database/Database.php
> +     * @param null $min
added a float option too

2022-11-03 11:16 UTC, fogelito commented on src/Database/Database.php
> +    public function decreaseDocumentAttribute(string $collection, string $id, string $attribute, int|float $value = 1, $min = null): bool
added a float option too

2022-11-07 12:57 UTC, fogelito commented on tests/Database/Base.php
> +        $this->assertEquals(false, static::getDatabase()->increaseDocumentAttribute('increase_decrease', $document->getId(), 'increase', 1, 102));
Done!

2022-12-08 04:03 UTC, abnegate approved these changes
Looks good! Just some conflicts to resolve

2023-02-03 03:20 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +        $sql = "update {$this->getSQLTable($name)} set `{$attribute}` = `{$attribute}` + :val WHERE _uid = :_uid" . $sqlMax . $sqlMin;
Let's use capitals for all SQL keywords for consistency

2023-02-03 03:20 UTC, abnegate commented on src/Database/Adapter/Postgres.php
> +        $sql = "update {$this->getSQLTable($name)} set \"{$attribute}\" = \"{$attribute}\" + :val WHERE _uid = :_uid" . $sqlMax . $sqlMin;
Let's use capitals for all SQL keywords for consistency

2023-02-05 10:34 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +        $sql = "update {$this->getSQLTable($name)} set `{$attribute}` = `{$attribute}` + :val WHERE _uid = :_uid" . $sqlMax . $sqlMin;
DONE :)

2023-02-05 10:34 UTC, fogelito commented on src/Database/Adapter/Postgres.php
> +        $sql = "update {$this->getSQLTable($name)} set \"{$attribute}\" = \"{$attribute}\" + :val WHERE _uid = :_uid" . $sqlMax . $sqlMin;
DONE :)

2023-02-08 07:56 UTC, abnegate approved these changes

2023-02-12 17:18 UTC, eldadfux approved these changes

2023-02-13 08:56 UTC, merged