Add Base Exception class
utopia-php/database pull request #218
Opened 2022-11-01 18:24 UTC by everly-gif

Following the changes in this [PR](https://github.com/appwrite/appwrite/pull/4575), we need to add some base Database Exception that we could use to distinguish between our errors and native errors. This PR implements a base exception class.

2022-11-04 03:55 UTC, christyjacob4 requested changes
Looks good 👌  

Can you also scan through the code base and check if there are usages of exceptions other than Utopia\Database\Exception or Utopia\Database\Exception\Authorization etc ? 

Basically we want to ensure that every custom error thrown by the database library is an instance of the Database library exception or its sub classes.

2022-11-04 17:20 UTC, everly-gif commented
> Looks good 👌
> 
> Can you also scan through the code base and check if there are usages of exceptions other than Utopia\Database\Exception or Utopia\Database\Exception\Authorization etc ?
> 
> Basically we want to ensure that every custom error thrown by the database library is an instance of the Database library exception or its sub classes.

I have updated every instance where we throw an exception to be a type of `Utopia\Database\Exception`. But there are still certain uses of `\Exception` such as places below

```
  try  {
            new \DateTime($datetime);
        }
        catch(\Exception $e) {
            return false;
        }
```
ie. in cases where we don't throw an exception explicitly.

2022-12-09 10:10 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +            throw new DatabaseException('Failed to commit transaction');
Let's hide this. We don't need to show this on the UI

2022-12-09 10:11 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +            throw new DatabaseException('Failed to commit transaction');
Let's hide this. We don't need to show this on the UI

2022-12-09 10:14 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +                    throw new DatabaseException('Unknown Type');
```suggestion
                    throw new DatabaseException('Unknown Type. Must be one of ${Database::VAR_BOOLEAN}, ...');
```

Can we format this error message to be more descriptive. Let's add all the types in the message

2022-12-09 10:15 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +                throw new DatabaseException('Unknown Type');
Same as the comment above

2022-12-09 10:17 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +                throw new DatabaseException('Unknown method:' . $method);
Let's make the message more descriptive like my comment above

2022-12-09 10:17 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +                throw new DatabaseException('Unknown Index Type:' . $type);
Same as above

2022-12-09 10:17 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +                throw new DatabaseException('Unknown Index Type:' . $type);
Same as above

2022-12-09 10:19 UTC, christyjacob4 commented on src/Database/Adapter/Mongo.php
> +                throw new DatabaseException('Unknown Operator:' . $operator);
```suggestion
                throw new DatabaseException('Unknown Operator:' . $operator . "Must be one of ..... ");
```
Let's make this message more descriptive

2022-12-09 10:19 UTC, christyjacob4 commented on src/Database/Adapter/Mongo.php
> +            default => throw new DatabaseException('Unknown sort order:' . $order),
same as above

2022-12-09 10:20 UTC, christyjacob4 commented on src/Database/Adapter/Mongo/MongoClient.php
> +use Utopia\Database\Document;
Can you sync your branch with the base branch ? I don't think this file is expected to be here.

2022-12-09 10:20 UTC, christyjacob4 commented on src/Database/Adapter/MySQL.php
> +                throw new DatabaseException('Unknown Index Type:' . $type);
Let's have a more descriptive error message

2022-12-09 10:24 UTC, christyjacob4 commented on src/Database/Adapter/SQLite.php
> +            throw new DatabaseException('Failed to commit transaction');
Let's hide this. We don't need to show this on the UI

2022-12-09 10:24 UTC, christyjacob4 commented on src/Database/Adapter/SQLite.php
> +            throw new DatabaseException('Failed to commit transaction');
Let's hide this. We don't need to show this on the UI

2022-12-09 10:26 UTC, christyjacob4 commented on src/Database/Adapter/SQLite.php
> +                throw new DatabaseException('Unknown Index Type:' . $type);
We need a more descriptive error message like my comments above

2022-12-09 10:26 UTC, christyjacob4 commented on src/Database/Adapter/SQLite.php
> +                throw new DatabaseException('Unknown Index Type:' . $type);
Same as above

2022-12-09 10:26 UTC, christyjacob4 commented on src/Database/Database.php
> +                throw new DatabaseException('Unknown attribute type: ' . $type);
More descriptive error message

2022-12-09 10:28 UTC, christyjacob4 commented on src/Database/Database.php
> +                throw new DatabaseException('Unknown attribute type: ' . $type);
More descriptive error message

2022-12-09 10:28 UTC, christyjacob4 commented on src/Database/Database.php
> +                        throw new DatabaseException('Unknown attribute type: ' . $type);
More descriptive error message

2022-12-09 10:28 UTC, christyjacob4 commented on src/Database/Database.php
> +                throw new DatabaseException('Unknown index type: ' . $type);
More descriptive error message

2022-12-09 10:41 UTC, christyjacob4 commented on src/Database/Validator/Roles.php
> +            } catch (Exception $e) {
Hmm.. is this necessary ? Do we need to explicitly import the native exception class ?

2022-12-09 10:41 UTC, christyjacob4 commented on src/Database/Role.php
> +use Utopia\Database\Exception as DatabaseException;
I don't think we need to expose these errors. Let's revert this file as its in the `main` branch

2022-12-09 11:26 UTC, christyjacob4 commented on src/Database/Query.php
> +            throw new DatabaseException("Invalid query method");
Okay after reviewing Role, Query and Permission I don't think we need to expose any of those errors in the UI either. Let's revert these files back too

2022-12-09 13:33 UTC, everly-gif commented on src/Database/Adapter/Mongo/MongoClient.php
> +use Utopia\Database\Document;
I am on the latest version of `main`

2022-12-16 16:27 UTC, christyjacob4 commented on src/Database/Adapter/MariaDB.php
> +                    throw new DatabaseException('Unknown Type. Must be one of ${Database::VAR_INTEGER}, ${Database::VAR_FLOAT}, ${Database::VAR_BOOLEAN}, ${Database::VAR_DOCUMENT}, ${Database::VAR_DA
```suggestion
                    throw new DatabaseException("Unknown Type. Must be one of ${Database::VAR_INTEGER}, ${Database::VAR_FLOAT}, ${Database::VAR_BOOLEAN}, ${Database::VAR_DOCUMENT}, ${Database::VAR_DATETIME}");
```

String interpolation only works when the string is enclosed in double quotes

2022-12-16 16:28 UTC, christyjacob4 commented on src/Database/Adapter/Mongo.php
> +                throw new DatabaseException('Unknown Operator:' . $operator .'. Must be one of ${Query::TYPE_EQUAL}, ${Query::NOTEQUAL, ${Query::TYPE_LESSER}, ${Query::TYPE_LESSEREQUAL}, ${Query::TYP
```suggestion
                throw new DatabaseException('Unknown Operator:' . $operator .". Must be one of ${Query::TYPE_EQUAL}, ${Query::NOTEQUAL}, ${Query::TYPE_LESSER}, ${Query::TYPE_LESSEREQUAL}, ${Query::TYPE_GREATER}, ${Query::TYPE_GREATEREQUAL}, ${Query::TYPE_CONTAINS}, {Query::TYPE_SEARCH}");
```

2022-12-16 16:35 UTC, everly-gif commented on src/Database/Adapter/Mongo/MongoClient.php
> +use Utopia\Database\Document;
removed this file

2023-02-22 09:47 UTC, eldadfux approved these changes

2023-04-28 06:01 UTC, merged