Timeout execution for mysql / mariadb
utopia-php/database pull request #220
Opened 2022-11-14 16:32 UTC by fogelito

2023-01-16 00:33 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +    }
Can we remove this? I don't think we use it anymore do we?

2023-01-16 00:33 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +    protected function setTimeoutSession(PDO|PDOProxy $pdo, int $milliseconds)
Lets rename this to `setTimeout` once we remove the other function. Then let's also add `setTimeout` to `Adapter.php` as an abstract function

2023-01-16 00:33 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +            // todo: Do we need to resetTimeoutSession here?
We will need to `resetTimeoutSession` here since the call in `find` is never reached if we throw the exception

2023-01-16 00:33 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +    protected function checkTimeoutException(PDOException $e): void
Let's rename this to `processException`, we could use it in future to handle other types of exceptions too

2023-01-16 00:33 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +            throw $e;
Let's remove this and throw it inside `checkTImeoutException`

2023-01-16 00:33 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +
```suggestion

        throw $e
```

2023-01-16 00:33 UTC, abnegate commented on src/Database/Adapter/SQLite.php
> +    }
We'll need to find a solution here too

2023-01-16 00:33 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +    }
Let's remove this

2023-01-16 00:33 UTC, abnegate commented on src/Database/Adapter/Mongo.php
> +    }
Let's remove this

2023-01-16 00:33 UTC, abnegate commented on src/Database/Adapter/SQLite.php
> +    }
Let's remove this

2023-01-16 00:33 UTC, abnegate commented on tests/Database/Base.php
> +    }
What's the difference between these two?

2023-01-16 00:33 UTC, abnegate commented on src/Database/Adapter.php
> +    abstract public function forceTimeoutException(): void;
Let's remove this

2023-01-16 00:34 UTC, abnegate commented
Let's update the title and description to be more descriptive for this PR

2023-01-17 08:45 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +            // todo: Do we need to resetTimeoutSession here?
Correct.
But when we throw the Exception it is the end of the script (besides the error hook) the session is over and the value is reset anyway?

2023-01-17 08:47 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +    protected function checkTimeoutException(PDOException $e): void
Like!

2023-01-17 08:47 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +            throw $e;
Like!

2023-01-17 08:55 UTC, fogelito commented on src/Database/Adapter/Mongo.php
> +    }
ok

2023-01-17 08:55 UTC, fogelito commented on src/Database/Adapter/SQLite.php
> +    }
ok

2023-01-17 08:58 UTC, fogelito commented on tests/Database/Base.php
> +    }
The first uses the find method with the sleep operator to create a timeout Exception.
The second directly writes the query making it easier to generate an exception.

2023-01-17 08:58 UTC, fogelito commented on src/Database/Adapter.php
> +    abstract public function forceTimeoutException(): void;
ok

2023-01-17 08:59 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +    }
ok

2023-01-17 09:14 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +            // todo: Do we need to resetTimeoutSession here?
I think so as well

2023-01-17 12:18 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +    protected function setTimeoutSession(PDO|PDOProxy $pdo, int $milliseconds)
Changing the name now.
This function is only for MariaDB instances not for Mongo.

2023-01-17 12:24 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +    }
From Eldad's comment on the RFC I had the feeling he was not sure which option to take?
I will comment it out.

2023-01-25 08:39 UTC, abnegate commented on src/Database/Query.php
> +    public static function sleep(string $attribute, array $values): self
Let's have a single `int $milliseconds` parameter here

2023-01-25 11:38 UTC, fogelito commented on src/Database/Query.php
> +    public static function sleep(string $attribute, array $values): self
Done!

2023-01-25 23:46 UTC, abnegate commented on src/Database/Query.php
> +    public static function sleep(string $attribute, int $milliseconds): self
We can remove the `$attribute` parameter too since it's unrelated to a `sleep` operator

2023-01-26 06:44 UTC, fogelito commented on src/Database/Query.php
> +    public static function sleep(string $attribute, int $milliseconds): self
Initially, this is how it was, I added this because I had a hard time with the index validator on Appwrite;
In the future when we remove the force indexes we can remove this.

2023-02-12 17:15 UTC, eldadfux requested changes

2023-02-12 17:15 UTC, eldadfux commented on src/Database/Adapter/Postgres.php
> +        if($timeout){
Wouldn't this stay persistent for future calls as well? we need to ensure timeout applies only to a given query.

2023-02-12 17:15 UTC, eldadfux commented on src/Database/Adapter.php
> +use Utopia\Database\Exception\Timeout;
This class is not used here at all.

2023-02-12 19:38 UTC, fogelito commented on src/Database/Adapter/Postgres.php
> +        if($timeout){
This happens on a find method where passed a timeout limitation.
Are you referring to the implementation of Postgres in particular?

2023-02-12 19:44 UTC, fogelito commented on src/Database/Adapter.php
> +use Utopia\Database\Exception\Timeout;
Currect.
The function processException function throws the Timeout Exception which looks different between
Sql.php:
processException(PDOException $e) 
Mongo:
processException(Exception $e): void

2023-02-23 07:27 UTC, fogelito commented on src/Database/Adapter.php
> +    abstract public function find(string $collection, array $queries = [], int $limit = 25, int $offset = 0, array $orderAttributes = [], array $orderTypes = [], array $cursor = [], string $cursorDir
Done!

2023-02-23 07:29 UTC, fogelito commented on src/Database/Query.php
> +            => true,
Done!

2023-02-23 07:30 UTC, fogelito commented on src/Database/Validator/Queries.php
> -
Done!

2023-02-23 07:36 UTC, fogelito commented on tests/Database/Base.php
> +                    '_data' => file_get_contents(__DIR__ . '/../longtext'),
Done!

2023-02-23 07:37 UTC, fogelito commented on tests/Database/Base.php
> +            $this->assertEquals(true, static::getDatabase()->createAttribute('timeouts', '_data', Database::VAR_STRING, 100000000, true));
Done!

2023-02-23 07:40 UTC, fogelito commented on tests/Database/Base.php
> +        if($this->getDatabase()->getAdapter()->getSupportForTimeouts()){
Done!

2023-02-27 06:46 UTC, abnegate commented on src/Database/Adapter/Mongo.php
> +        '$where',
Do we need this? I don't see it used in the PR

2023-02-27 06:47 UTC, abnegate commented on src/Database/Adapter/Mongo.php
> +            Throw new Timeout($e->getMessage());
```suggestion
            throw new Timeout($e->getMessage());
```

2023-02-27 08:34 UTC, abnegate commented on src/Database/Adapter/Postgres.php
> +                $value = "'{$value}*'";
I don't think this change should be here

2023-02-27 08:35 UTC, abnegate commented on src/Database/Adapter/Postgres.php
> +                    $conditions[] = $attribute.' '.$this->getSQLOperator($query->getMethod()).' :'.$placeholder.'_'.$key; //
Let's remove the comment at end of line

2023-02-27 08:36 UTC, abnegate commented on src/Database/Adapter/SQL.php
> +        /** @var PDOStatement $stmt */
Let's remove this, from the Appwrite side it's a `PSOStatementProxy`

2023-02-27 08:37 UTC, abnegate commented on src/Database/Database.php
> +    public function find(string $collection, array $queries = [], $timeout = null): array
We're missing the `?int` type here too

2023-02-27 08:58 UTC, fogelito commented on src/Database/Adapter/Mongo.php
> +        '$where',
I was using this for the sleep  operation removed for now...

2023-02-27 09:12 UTC, fogelito commented on src/Database/Adapter/Mongo.php
> +            Throw new Timeout($e->getMessage());
Done forgot to update

2023-02-27 09:19 UTC, fogelito commented on src/Database/Adapter/Postgres.php
> +                $value = "'{$value}*'";
you are right 
I think this too should not be here:
$value = $this->getSQLValue($query->getMethod(), $value);
as it is in master

2023-02-27 09:23 UTC, fogelito commented on src/Database/Adapter/Postgres.php
> +                $value = "'{$value}*'";
Yep, Revert...

2023-02-27 09:29 UTC, fogelito commented on src/Database/Adapter/Postgres.php
> +                    $conditions[] = $attribute.' '.$this->getSQLOperator($query->getMethod()).' :'.$placeholder.'_'.$key; //
Done!

2023-02-27 09:32 UTC, fogelito commented on src/Database/Adapter/SQL.php
> +        /** @var PDOStatement $stmt */
done!

2023-02-27 09:38 UTC, fogelito commented on src/Database/Database.php
> +    public function find(string $collection, array $queries = [], $timeout = null): array
Done!

2023-02-27 09:45 UTC, fogelito commented on src/Database/Database.php
> +    public function find(string $collection, array $queries = [], $timeout = null): array
Done!

2023-02-27 09:53 UTC, fogelito commented on src/Database/Adapter/Postgres.php
> +                $value = "'{$value}*'";
Not sure we want the "*" on the function return value for Postgres

2023-02-27 10:03 UTC, abnegate commented on src/Database/Adapter/Postgres.php
> +                $value = "'{$value}*'";
Not 100% sure, but it was there when Postgres was merged and tests are passing with it

2023-03-01 13:28 UTC, abnegate commented on src/Database/Adapter/SQL.php
> +
Let's just have one line separating code blocks

2023-03-02 09:28 UTC, fogelito commented on src/Database/Adapter/SQL.php
> +
Done!

2023-03-06 01:54 UTC, abnegate reviewed
Looks like one of the tests needs to be updated after merging in main

2023-03-06 10:59 UTC, abnegate approved these changes

2023-03-06 11:05 UTC, eldadfux commented on src/Database/Adapter/Mongo.php
> +        return true; // todo: temporary
Why this is temporary?

2023-03-06 11:39 UTC, fogelito commented on src/Database/Adapter/Mongo.php
> +        return true; // todo: temporary
Removed, We find a solution for Mongo as well 👍

2023-03-06 11:41 UTC, fogelito commented on src/Database/Adapter.php
> +    abstract public function getSupportForTimeouts(): bool;
Done!

2023-03-07 10:16 UTC, eldadfux approved these changes

2023-03-07 13:33 UTC, merged