draft: collection level permissions
utopia-php/database pull request #262
Opened 2023-04-18 00:13 UTC by TorstenDittmann

2023-04-18 00:17 UTC, stnguyen90 requested changes

2023-04-18 00:17 UTC, stnguyen90 commented on src/Database/Database.php
> +        }
I don't think this check should be only for `documentSecurity == true`. What if `documentSecurity` is `true` AND there are collection-level permissions?

Same for the `count()` method.

2023-04-18 00:42 UTC, stnguyen90 requested changes

2023-04-18 00:42 UTC, stnguyen90 commented on src/Database/Database.php
> +                $isValid = $documentSecurity ? $validator->isValid($document->getRead()) : $validator->isValid($collection->getRead());
Would this ignore collection level permissions if `documentSecurity` was `true`?

2023-04-18 22:47 UTC, stnguyen90 commented on src/Database/Database.php
> +        }
The outer if check should be removed here, right?

2023-04-18 22:59 UTC, TorstenDittmann commented on src/Database/Database.php
> +        }
good catch, leftover

2023-04-20 23:54 UTC, stnguyen90 commented on src/Database/Database.php
> +                ));
I think this needs to check if `$value == null` before deleting or else you we get:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/1477010/233509991-4290d15f-acb2-4b83-855f-0df84bcf5ee9.png">

2023-04-21 00:42 UTC, stnguyen90 commented on src/Database/Database.php
> +                    ));
Should this always skip? If it does, we'll have a limitation where related documents will only delete 1 level deep. For example, if i have:

> Quiz -> Questions -> Answer Choices

and I delete the Quiz, the Questions will be deleted, but the Answer Choices won't be.

2023-04-21 00:59 UTC, stnguyen90 commented
When setting a relationship, if a document with the specified ID doesn't exist, the API call will still succeed, but the relationship will be set to null.

2023-04-21 17:56 UTC, stnguyen90 commented on src/Database/Database.php
> +                    ));
I've created a task for us to track this.

2023-04-24 16:19 UTC, stnguyen90 commented on src/Database/Database.php
> +            if (!$authorization->isValid($collection->getCreate())) {
@fogelito, I don't think we need to for `createDocument()`, right? That should only be on the collection level.

2023-04-24 18:04 UTC, stnguyen90 approved these changes

2023-04-25 05:25 UTC, fogelito commented on tests/Database/Base.php
> +            '$permissions' => [
If documentSecurity is false for $collection , do we need to pass permissions on createDocument?

2023-04-25 07:17 UTC, fogelito commented on src/Database/Database.php
> +
Do we need to clean cache?

2023-04-25 07:58 UTC, fogelito commented on src/Database/Database.php
> +
Can you add a test for the method?

2023-04-25 10:30 UTC, TorstenDittmann commented on src/Database/Database.php
> +
This should be covered by `$this->updateDocument`. Adding a test 👍🏻

2023-04-26 04:31 UTC, merged