Feat - Expand Permissions validator
utopia-php/database pull request #27
Opened 2021-06-21 22:44 UTC by kodumbeats

This PR expands the permissions validator to check the format of the permission strings. Since the removal of the wildcard char `*`, a "role" satisfies the following simple schema:
- Can be expressed in the format `{$type}:{$value}` with only a single colon separating the permission type from its value
- `$type` must be one of `['member', 'role', 'user', 'team']`
- `$value` must not be empty
- `$value` must satisfy the Key validator for `user` and `member`
- `$value` must be one of `['all', 'guest', 'member']` when `$type = 'role'`
- Since `team:[teamId]/[role]` can have any string for role, no validation needed

### Test plan
Unit tests included

2021-06-22 10:42 UTC, eldadfux commented
@kodumbeats Maybe we should introduce some rules for the `role` part? maybe same rules as for a key?

2021-06-23 15:22 UTC, eldadfux requested changes

2021-06-23 15:22 UTC, eldadfux commented on src/Database/Validator/Permissions.php
>                          $this->message = $key->getDescription();
Not sure the message here is verbose enough, maybe we should have a custom one.

2021-06-23 15:22 UTC, eldadfux commented on tests/Database/Validator/PermissionsTest.php
> +        $this->assertEquals($object->isValid(['team:ab(124']), false);
Maybe we should add more tests for the new role validation, for example: `team:xyz/hello world` -> false

2021-06-23 15:33 UTC, kodumbeats commented on tests/Database/Validator/PermissionsTest.php
> +        $this->assertEquals($object->isValid(['team:ab(124']), false);
Of course 🤯 I incorrectly assumed the form of the teams permission as `'team:teamID' OR 'team:role'`. Will improve this testing.

2021-06-23 15:47 UTC, christyjacob4 commented on src/Database/Validator/Permissions.php
> +            if ($role === '*') {
This is a nice touch :wink:

2021-06-23 15:54 UTC, christyjacob4 commented on src/Database/Validator/Permissions.php
> +                    if (!$key->isValid($value)) {
Is the Key() validator able to check if the `id` exists in the database? 
Do we plan to have support for that ?

2021-06-23 15:56 UTC, christyjacob4 approved these changes
Looks really clean :superhero: . Nice one!

2021-06-23 20:28 UTC, kodumbeats commented on src/Database/Validator/Permissions.php
> +                    if (!$key->isValid($value)) {
I'm not sure we want to do that in this library, with separation of concerns from Appwrite and such. @eldadfux what do you think?

2021-06-23 20:30 UTC, kodumbeats commented on src/Database/Validator/Permissions.php
>                          $this->message = $key->getDescription();
Is this appropriately verbose? 951ea03

2021-06-23 20:30 UTC, kodumbeats commented on tests/Database/Validator/PermissionsTest.php
> +        $this->assertEquals($object->isValid(['team:ab(124']), false);
Added more validation+testing in 2756069

2021-06-24 05:45 UTC, lohanidamodar commented on src/Database/Validator/Permissions.php
> +                        // Split into format {$teamId}:{$teamRole}
```suggestion
                        // Split into format {$teamId}/{$teamRole}
```

2021-06-24 05:46 UTC, lohanidamodar reviewed
LGTM

2021-06-24 15:49 UTC, eldadfux commented on src/Database/Validator/Permissions.php
>                          $this->message = $key->getDescription();
Not sure I feel like its clear enough that we're talking about the role part: team:[teamid]/**role** Maybe emphasizing: "The role section has..."

2021-06-24 15:52 UTC, eldadfux commented on tests/Database/Validator/PermissionsTest.php
> +        $this->assertEquals($object->isValid(['team:ab(124']), false);
Do we allow `_` if not in the first character?

2021-06-24 15:53 UTC, eldadfux commented on src/Database/Validator/Permissions.php
> +                    if (!$key->isValid($value)) {
I agree, and I would also be concerned about the performance cost. + we might want to validate the ID with no regard to the database (team role for example)

2021-06-26 21:24 UTC, kodumbeats commented on tests/Database/Validator/PermissionsTest.php
> +        $this->assertEquals($object->isValid(['team:ab(124']), false);
If I'm reading this regex correctly, yes:
https://github.com/utopia-php/database/blob/feat-permission-validator-expanded/src/Database/Validator/Key.php#L45-L46

2021-06-26 21:50 UTC, kodumbeats commented on src/Database/Validator/Permissions.php
>                          $this->message = $key->getDescription();
Tried again in f349a13 🤔

2021-06-29 13:54 UTC, merged