Updated Documentation.
utopia-php/database pull request #277
Opened 2023-05-27 17:16 UTC by faisalill

2023-05-29 09:35 UTC, abnegate reviewed
Let's follow

2023-05-29 09:35 UTC, abnegate commented on README.md
> +use Utopia\Cache\Adapter\Memory as MemoryCache;
Let's remove the alias and just use `Memory`, we can tell from the usage it is a cache type since it is wrapped in `new Cache()`, applies to all examples

2023-05-29 09:35 UTC, abnegate commented on README.md
> +$dbPort = 27017; // this should be a integer
> // this should be a integer

Let's remove this comment, it should be made clear from the usage in an IDE

2023-05-29 09:35 UTC, abnegate commented on README.md
> +$nameOfTheDatabaseOrSchema = 'mydb';
Let's just use `name` here to be more succinct

2023-05-29 09:35 UTC, abnegate commented on README.md
> +//delete database
Let's keep consistent formatting for all of the comments:

```suggestion
// Delete database
```

2023-05-29 09:35 UTC, abnegate commented on README.md
> +// The second table is named '$namespace_$collectionName_perms' with column names '_id', '_type', '_permission', '_document'
Let's move all the comments above the code and use agnostic terms: collection instead of table, attribute instead of column etc.

2023-05-29 09:35 UTC, abnegate commented on README.md
> +$database->createAttribute($collectionName, $newAttributeId,$attributeType[0] , $attributeSize, $attributeRequired,$defaultValue, $isSigned, $isAnArray, $format, $formatOptions, $filters);
Let's follow the same format we had previously but just add the missing methods, and use named parameters:

```php
// Add attributes
$database->createAttribute('movies', 'name', Database::VAR_STRING, 128, true);
$database->createAttribute('movies', 'director', Database::VAR_STRING, 128, true);
...
```

This will keep it simple and easy to read

2023-05-30 09:29 UTC, faisalill commented
@abnegate 
Did the changes

2023-05-30 11:32 UTC, abnegate commented on README.md
> +$database->setNamespace(name: "namespace");
Let's use single quotes for these parameters

2023-05-30 11:32 UTC, abnegate commented on README.md
> +         '$id' => ID::custom('attribute1'),
Let's use more meaningful names for the attributes and indexes here

2023-05-30 11:32 UTC, abnegate commented on README.md
> +// Creates two new collection named '$namespace_$collectionName' with attribute names '_id', '_uid', '_createdAt', '_updatedAt', '_permissions'
Let's have a separate section detailing the default attributes

2023-05-30 11:32 UTC, abnegate commented on README.md
> +$database->createAttribute(collection: "movies",id: "name",type:  $attributeType[0], size: 128, required: true);
Let's use line breaks so each parameter is on a new line to improve readability for all the `createAttribute` calls. Also using single quotes instead of double

```suggestion
$database->createAttribute(
    collection: 'movies',
    id: 'name',
    type: $attributeTypes[0],
    size: 128, 
    required: true
);
```

2023-05-30 11:32 UTC, abnegate commented on README.md
> +[
Let's use a plural for the array variable name and open the arrays on the same line:

```suggestion
$attributeTypes = [
```

2023-05-30 11:32 UTC, abnegate commented on README.md
> +[
Same as above here

2023-05-30 11:32 UTC, abnegate commented on README.md
> +use Utopia\Database\Document;             // remember to use these classes
> // remember to use these classes

Let's remove this comment

2023-05-30 11:32 UTC, abnegate commented on README.md
> +    Permission::delete(Role::user(ID::custom(id: "my_user_3235"))
Let's outdent these since there is no nesting

2023-05-30 11:32 UTC, abnegate commented on README.md
> +    ID::unique(padding: 12),        // Length of the ID: Default is 7
`padding` here is the number of extra chars to add to the ID on top of the default of 13. So using 12 here the ID length will be 25

2023-05-30 11:32 UTC, abnegate commented on README.md
> +    ID::custom(id: "my_user_3235")  // a parameter must be passed
Let's remove the comment here

2023-05-30 11:32 UTC, abnegate commented on README.md
> +    Role::user(ID::unique())    // creates a role with $customId as the identifier
Let's remove the comment here

2023-05-30 11:32 UTC, abnegate commented on README.md
> +// To get which collection a document belongs to
Let's remove the `To` before these comments

2023-05-30 11:32 UTC, abnegate commented on README.md
> +    Query::select($attributes),
Let's inline the `$attributes` variable here

2023-05-30 11:32 UTC, abnegate commented on README.md
> +   Query::offset(value: 0),
Let's remove the parameter names here

2023-05-31 04:21 UTC, faisalill commented
@abnegate , 
Did the changes as you said.

2023-07-17 11:49 UTC, adityaoberai reviewed
Left some comments

@gewenyu99 might need some of your opinions on how headings should be managed across the Readme file

2023-07-17 11:49 UTC, adityaoberai commented on README.md
> +## Code Examples
Code here would anyway be implicitly understood, so I think we can let it be

```suggestion
## Examples
```

2023-07-17 11:49 UTC, adityaoberai commented on README.md
> +> ## Below methods are available for all database adapters.
```suggestion
> Below methods are available for all database adapters.
```

This does not need to be a heading within the note

2023-07-17 11:58 UTC, faisalill commented on README.md
> +## Code Examples
Done

2023-07-17 11:58 UTC, faisalill commented on README.md
> +> ## Below methods are available for all database adapters.
Done

2023-07-17 20:44 UTC, stnguyen90 requested changes
Great PR! 🤯 I left some comments during the review, please check them out.

2023-07-17 20:44 UTC, stnguyen90 commented on README.md
> +### Setting up different database adapters
The other heading are capitalized so let's do the same with these.

2023-07-17 20:44 UTC, stnguyen90 commented on README.md
> +**MariaDB:**
Let's use headings for these too.

2023-07-17 20:44 UTC, stnguyen90 commented on README.md
> +**Database Methods:**
Let's make these headings and put it under a Using Database Adapters heading:

```suggestion
### Using database adapters

#### Database Methods
```

2023-07-17 20:44 UTC, stnguyen90 commented on README.md
> +| SQLlite  | ✅     | 3.38    |
```suggestion
| SQLite   | ✅     | 3.38    |
```

2023-07-17 20:44 UTC, stnguyen90 commented on README.md
>  ### Adapters
I don't think it makes sense for Adapters to be under Examples. Maybe it should be a level 2 heading or be under Getting Started. What do you think?

2023-07-18 14:41 UTC, gewenyu99 commented
I have no comments beyond what has been mentioned by Steven. Great PR!

2023-07-18 18:17 UTC, faisalill commented on README.md
> +**MariaDB:**
Done

2023-07-18 18:21 UTC, faisalill commented on README.md
> +**Database Methods:**
Created a new section for it with a different name.
Refer https://github.com/faisalill/database/blob/better-readme/README.md?plain=1#L104

2023-07-18 18:22 UTC, faisalill commented on README.md
>  ### Adapters
Renamed it to Supported Databases (since that what this section was about).
And placed it after Limitations Section.

2023-07-18 18:41 UTC, stnguyen90 requested changes

2023-07-18 18:41 UTC, stnguyen90 commented on CONTRIBUTING.md
> +
I don't think a table of contents is necessary since GitHub already shows an outline on the right:

<img width="1401" alt="image" src="https://github.com/utopia-php/database/assets/1477010/3c7615da-bd50-4af2-b34c-cfcb2ad9b711">

2023-07-18 18:41 UTC, stnguyen90 commented on CONTRIBUTING.md
> +## How to Start
How come the question mark was removed?

2023-07-18 18:41 UTC, stnguyen90 commented on CONTRIBUTING.md
> -## Submit a Pull Request 🚀
How come the emoji was removed?

2023-07-18 18:41 UTC, stnguyen90 commented on README.md
> +
Again, probably no need for manual table of contents.

2023-07-18 18:41 UTC, stnguyen90 commented on README.md
> +` ✅  - supported, 🛠  - work in progress`
This is a bit harder to read as horizontal. Does vertical look clearer?

2023-07-18 18:41 UTC, stnguyen90 commented on README.md
> +#### Database Methods
I don't think the heading level is right here:

```suggestion
### Database Methods
```

2023-07-18 18:41 UTC, stnguyen90 commented on README.md
> +### Connecting to a database
This should be title case

2023-07-18 18:41 UTC, stnguyen90 commented on README.md
> +**MariaDB:**
This is still just bolded.

2023-07-18 18:41 UTC, stnguyen90 commented on README.md
>  ## Copyright and license
Would you please also make this title case

2023-07-19 02:14 UTC, faisalill commented on CONTRIBUTING.md
> +
Removed table of contents.

2023-07-19 02:16 UTC, faisalill commented on CONTRIBUTING.md
> +## How to Start
Removed it so that I could link it in the table of contents. 
Added it back since table of contents is removed.

2023-07-19 02:16 UTC, faisalill commented on CONTRIBUTING.md
> -## Submit a Pull Request 🚀
Removed it so that I could link it in the table of contents. 
Added it back since table of contents is removed.

2023-07-19 02:17 UTC, faisalill commented on README.md
> +
Removed it

2023-07-19 02:17 UTC, faisalill commented on README.md
> +#### Database Methods
Fixed it.

2023-07-19 02:17 UTC, faisalill commented on README.md
> +#### Database Methods
Fixed it.

2023-07-19 02:19 UTC, faisalill commented on README.md
> +### Connecting to a database
Done

2023-07-19 02:19 UTC, faisalill commented on README.md
>  ## Copyright and license
Done

2023-07-19 02:25 UTC, faisalill commented on README.md
> +` ✅  - supported, 🛠  - work in progress`
Made it vertical. Looks better to read.

2023-07-22 01:07 UTC, stnguyen90 commented on README.md
> +` ✅  - supported, 🛠  - work in progress`
Ooops. Sorry, I meant just the legend rather than the table 😬

2023-07-22 01:09 UTC, stnguyen90 reviewed
Left 1 comment: https://github.com/utopia-php/database/pull/277#discussion_r1271188562

Otherwise, this looks beautiful!

2023-07-22 15:28 UTC, faisalill commented on README.md
> +` ✅  - supported, 🛠  - work in progress`
Done

2023-07-25 17:26 UTC, abnegate commented on README.md
> +    Database::RELATION_ONE_TO_ONE,,
```suggestion
    type: Database::RELATION_ONE_TO_ONE,
```

2023-07-25 17:26 UTC, abnegate commented on README.md
> +    Database::RELATION_ONE_TO_ONE,
```suggestion
    type: Database::RELATION_ONE_TO_ONE,
```

2023-07-25 17:26 UTC, abnegate commented on README.md
> +Role::user(ID::unique())
Let's include all the available role helpers here

2023-07-25 17:26 UTC, abnegate commented on README.md
> +$document = new Document([
We need to include the `$id` attribute for the new Document here

2023-07-25 17:26 UTC, abnegate commented on README.md
> +    max: 0 // max = 0 means no limit
> // max = 0 means no limit

This is no longer true, now passing `null` (the default value) means no limit

2023-07-25 17:26 UTC, abnegate commented on README.md
> +);
```suggestion
$database->count(
    collection: 'movies', 
    queries:  [
        Query::equal(attribute: 'name', values: ['Captain Marvel']),
        Query::greaterThan(attribute: 'year', value: 2019)
    ], 
    max: 1000 // Max is optional
);
```

2023-07-25 17:26 UTC, abnegate commented on README.md
> +);
Let's add a note that cached documents/collections are automatically deleted when the document/collection is updated or deleted

2023-07-26 18:59 UTC, abnegate commented on README.md
> +    type: Database::RELATION_ONE_TO_ONE,,
```suggestion
    type: Database::RELATION_ONE_TO_ONE,
```

2023-07-26 19:00 UTC, abnegate approved these changes

2023-07-26 21:37 UTC, stnguyen90 approved these changes

2023-07-26 21:47 UTC, merged