No Exception when no change in update document function
utopia-php/database pull request #295
Opened 2023-07-18 16:24 UTC by fanatic75

We should not throw authorization exception when there is no change in update document coming document.
This is required for Relationships as we need to allow users to update document of related collection.

2023-07-18 19:35 UTC, stnguyen90 requested changes

2023-07-18 19:35 UTC, stnguyen90 commented on src/Database/Database.php
> +            //compare if the document any changes
Let's be consistent with the style:

```suggestion
            // Compare if the document has any changes
```

2023-07-18 19:35 UTC, stnguyen90 commented on src/Database/Database.php
> +                //skip the nested documents as they will be checked later in recursions.
```suggestion
                // Skip the nested documents as they will be checked later in recursions.
```

2023-07-18 19:35 UTC, stnguyen90 commented on tests/Database/Base.php
> +        //no changes in document
```suggestion
        // No changes in document
```

2023-07-18 19:35 UTC, stnguyen90 commented on tests/Database/Base.php
> +        $documentToUpdate->setAttribute('$createdAt', $document->getAttribute('$createdAt'));
`$createdAt` shouldn't change, right?

2023-07-18 19:35 UTC, stnguyen90 commented on tests/Database/Base.php
> +        $documentToUpdate->setAttribute('$updatedAt', $document->getAttribute('$updatedAt'));
It seems odd to allow someone without access to update`$updatedAt` when they don't have access, just by issuing an update with the same values 🧐

2023-07-18 19:52 UTC, fanatic75 commented on tests/Database/Base.php
> +        $documentToUpdate->setAttribute('$createdAt', $document->getAttribute('$createdAt'));
Since we are creating a new document using the Document constructor, I am purposefully setting  createdAt and updatedAt as document constructor doesn't add those attributes. 
Update document requires both of those attributes for MongoDB in the coming document.

2023-07-18 19:52 UTC, fanatic75 commented on tests/Database/Base.php
> +        $documentToUpdate->setAttribute('$updatedAt', $document->getAttribute('$updatedAt'));
We are not updating updateAt. We are just adding those attributes in the document that needs to be updated which is required for MongoDB.

2023-07-18 20:22 UTC, fanatic75 commented on tests/Database/Base.php
> +        $documentToUpdate->setAttribute('$updatedAt', $document->getAttribute('$updatedAt'));
Okay, due to relationships, there can be a change in a child document, so we cannot skip updating the document even if there is no change and have no permission to that collection

2023-07-19 08:28 UTC, fanatic75 commented on tests/Database/Base.php
> +        $documentToUpdate->setAttribute('$updatedAt', $document->getAttribute('$updatedAt'));
Skipping updating the time when there is no change in document

2023-07-24 22:56 UTC, stnguyen90 approved these changes
LGTM. I'll defer to @abnegate for another set of eyes.

2023-07-25 07:15 UTC, fogelito commented on tests/Database/Base.php
>          sleep(1);
No need for sleep on getDocument

2023-07-25 10:23 UTC, fanatic75 commented on tests/Database/Base.php
>          sleep(1);
That's not an addition in this PR. If you think we should drop it, we can remove that from a testcase in a refactor PR?

2023-07-25 22:22 UTC, abnegate commented on src/Database/Database.php
> +        $skipPermission = true;
Let's rename this from `skipPermission` to `shouldUpdate`, it will make the usage more clear

2023-07-25 22:22 UTC, abnegate commented on src/Database/Database.php
> +                if ($old->getAttribute($key) instanceof Document) {
Let's cache the old value so we only have to lookup the key once for the best case

2023-07-25 22:22 UTC, abnegate commented on tests/Database/Base.php
> +
Let's add only one blank line between code blocks

2023-07-25 22:22 UTC, abnegate commented on tests/Database/Base.php
> +        Authorization::cleanRoles();
We don't need this both here and at the start of the function

2023-07-25 22:22 UTC, abnegate commented on tests/Database/Base.php
> +        $updatedDocument = static::getDatabase()->updateDocument('documents', $document->getId(), $documentToUpdate);
Instead of recreating the document with the same values, you can just try passing the `$document` returned from create directly to the update function

2023-07-26 05:33 UTC, fanatic75 commented on src/Database/Database.php
> +        $skipPermission = true;
Done this

2023-07-26 05:33 UTC, fanatic75 commented on src/Database/Database.php
> +                if ($old->getAttribute($key) instanceof Document) {
Here old is coming from the get document; it should already be cached; also, in every recursion call, $old changes.

2023-07-26 05:34 UTC, fanatic75 commented on tests/Database/Base.php
> +        Authorization::cleanRoles();
removed it from beginning

2023-07-26 05:34 UTC, fanatic75 commented on tests/Database/Base.php
> +        $updatedDocument = static::getDatabase()->updateDocument('documents', $document->getId(), $documentToUpdate);
passed $document directly.

2023-07-26 05:35 UTC, fanatic75 commented
@abnegate  can you please re-review this

2023-07-26 15:54 UTC, fanatic75 commented on src/Database/Database.php
> +                if ($old->getAttribute($key) instanceof Document) {
done this, added a variable for holding oldAttributeValue

2023-07-26 18:02 UTC, abnegate approved these changes

2023-07-26 18:03 UTC, merged