Feat - add custom filter parser
utopia-php/database pull request #3
Opened 2021-04-22 18:06 UTC by kodumbeats

## New Feature
This PR introduces methods to the `Database` class to parse an array of string filters.

Note - due to `$filter` being used already, I refer to a custom filter as a `$query` until we can find something more clear. 

## Test plan
Tests included with PR

2021-04-22 18:13 UTC, kodumbeats commented
Testing locally against MariaDB has 🟢 
```bash
$ docker-compose exec tests vendor/bin/phpunit --debug /usr/src/code/tests/Database/Adapter/MariaDBTest.php

PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDelete' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDelete' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDeleteCollection' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDeleteCollection' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDeleteAttribute' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDeleteAttribute' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDeleteIndex' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDeleteIndex' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDocument' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDocument' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testGetDocument' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testGetDocument' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testUpdateDocument' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testUpdateDocument' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testDeleteDocument' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testDeleteDocument' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testFindFirst' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testFindFirst' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testFindLast' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testFindLast' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testParseQueries' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testParseQueries' ended


Time: 00:03.764, Memory: 6.00 MB

OK (11 tests, 101 assertions)
```

2021-04-23 05:38 UTC, eldadfux commented
Thinking about this a bit here are some of my ideas:
- We will create a class called `Database\Query` to hold all query related operations/data
- The class constructor will create a query instance with all relevant metadata that will allow us to build a native SQL/NOSQL query (key, operator, value/values), an array of query objects will allow us to build complex queries.
- Create a static method called `Database\Query::parse([STRING])` that will parse a string query (`director.equals('brandon')`) and return a `Database\Query` instance.
- The `Database\Query` class can have multiple getters and setters to make DX nicer.

2021-04-23 16:32 UTC, kodumbeats commented
As of e802153
```bash
# kodumbeats @ magician in ~/w/kodumbeats/database on git:v0 x [12:28:00]
$ dc exec tests vendor/bin/phpunit tests/Database/Adapter/MariaDBTest.php 
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

..........                                                        10 / 10 (100%)

Time: 00:00.711, Memory: 6.00 MB

OK (10 tests, 85 assertions)

# kodumbeats @ magician in ~/w/kodumbeats/database on git:v0 x [12:28:17] 
$ dc exec tests vendor/bin/phpunit tests/Database/QueryTest.php          
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 00:00.002, Memory: 6.00 MB

OK (2 tests, 10 assertions)

```

2021-04-23 16:44 UTC, eldadfux requested changes

2021-04-23 16:44 UTC, eldadfux commented on src/Database/Query.php
> +    public function __construct($attribute, $operator, $operand)
Maybe $value instead of $operand might be a better fit?

2021-04-23 16:44 UTC, eldadfux commented on src/Database/Query.php
> +    public function __construct($attribute, $operator, $operand)
Missing types for $attribute and $operator

2021-04-23 16:44 UTC, eldadfux commented on src/Database/Query.php
> +    public function __construct($attribute, $operator, $operand)
Can we assume $operand / $value are always arrays? this will make support for `or` queries simpler

2021-04-23 16:44 UTC, eldadfux commented on src/Database/Query.php
> +        endswitch;
In PHP this `endswitch` syntax is more common for PHTML templates and not standard code, you can use `{}` instead.

2021-04-23 16:44 UTC, eldadfux commented on src/Database/Query.php
> +    public static function parseExpression(string $expression): array
Might make more sense to have this as a protected static method?

2021-04-23 16:44 UTC, eldadfux commented on src/Database/Query.php
> +    // /**
Love this idea! we should probably have a validator class for queries syntax...

2021-04-23 17:09 UTC, kodumbeats commented on src/Database/Query.php
> +    public static function parseExpression(string $expression): array
I tried the same at first but hit this error:
```
2) Utopia\Tests\QueryTest::testParseExpression
Error: Call to protected method Utopia\Database\Query::parseExpression() from context 'Utopia\Tests\QueryTest'

/usr/src/code/tests/Database/QueryTest.php:35
```

2021-04-23 18:04 UTC, kodumbeats commented on src/Database/Query.php
> +    public function __construct($attribute, $operator, $operand)
> Can we assume $operand / $value are always arrays? this will make support for `or` queries simpler

Sure! I've refactored it to `$expression: [$operator => $value]`

2021-04-23 19:00 UTC, eldadfux commented on src/Database/Query.php
> +    public static function parseExpression(string $expression): array
You can't test protected methods... which is completely fine if the other tests cover that protected logic...

2021-04-23 19:23 UTC, kodumbeats commented
As of 8c8afb3
```bash
# kodumbeats @ magician in ~/w/kodumbeats/database on git:v0 x [15:22:50] 
$ dc exec tests vendor/bin/phpunit tests/Database/Adapter/MariaDBTest.php  
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

................                                                  16 / 16 (100%)

Time: 00:00.721, Memory: 6.00 MB

OK (16 tests, 94 assertions)

# kodumbeats @ magician in ~/w/kodumbeats/database on git:v0 x [15:22:59] 
$ dc exec tests vendor/bin/phpunit tests/Database/QueryTest.php          
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 00:00.002, Memory: 6.00 MB

OK (2 tests, 10 assertions)
```

2021-04-23 19:26 UTC, kodumbeats commented on src/Database/Query.php
> +    public static function parseExpression(string $expression): array
This is my problem then: I call one function in the other:
https://github.com/utopia-php/database/pull/3/files#diff-35b0686b57f21084e677c6f36a52de692612fb03fff51a477b43c6bd3ac7993cR99

Should I just refactor the logic of `parseExpression()` into `parse()`?

2021-04-23 19:29 UTC, kodumbeats commented on src/Database/Query.php
> +    public function __construct($attribute, $operator, $operand)
> > Can we assume $operand / $value are always arrays? this will make support for `or` queries simpler
> 
> Sure! I've refactored it to `$expression: [$operator => $value]`

Didn't have much luck with this approach - curious to know where how you'd like to expose the $expression array:
https://github.com/utopia-php/database/pull/3/commits/1c6e60c20f7afcd8639a55b8fb56c4acfb0cdf7d

2021-04-23 19:30 UTC, kodumbeats commented on src/Database/Query.php
> +    // /**
How's this for a start? I figure this is a good place to check if the operator is supported too:
https://github.com/utopia-php/database/pull/3/commits/179a0d51da3db2313a9c7662ebcc593b68d0c1f0

2021-04-23 19:36 UTC, eldadfux commented on src/Database/Query.php
> +    public static function parseExpression(string $expression): array
use `self::` not `Query::`

2021-04-23 19:38 UTC, eldadfux commented on src/Database/Query.php
> +    // /**
Looks like a good start, we can have it as a standalone PR

2021-04-23 19:41 UTC, eldadfux requested changes

2021-04-23 19:41 UTC, eldadfux commented on src/Database/Query.php
> +                [$operator, $value] = Query::parseExpression($input[1]);
Not sure what this change is doing

2021-04-23 19:41 UTC, eldadfux commented on src/Database/Query.php
> +    public function __construct(string $attribute, string $operator, $value)
My idea for supporting `or` queries was set $value as array and maybe call it `$values`

2021-04-23 21:12 UTC, kodumbeats commented on src/Database/Query.php
> +                [$operator, $value] = Query::parseExpression($input[1]);
Clarified in 7071923

2021-04-23 21:13 UTC, kodumbeats commented on src/Database/Query.php
> +    public function __construct(string $attribute, string $operator, $value)
Introduced in e3f1efb, though it means we have to do more work with appropriately typecasting here.

2021-04-23 21:15 UTC, kodumbeats commented on src/Database/Query.php
> +    public static function parseExpression(string $expression): array
Even with `self::`, `phpunit` throws the same error. Since we construct via a static method instead of the constructor, we have additional constraints.
Commit: 7071923

2021-04-23 21:23 UTC, kodumbeats commented on src/Database/Query.php
> +    public static function parseExpression(string $expression): array
My misunderstanding! Addressed 👍🏻

2021-04-25 15:32 UTC, eldadfux commented
We also need to support multiple params for `or` queries, a few examples:

`director.equals('eldad', 'brandon')`
`director.equals('eldad','brandon')`

2021-04-26 15:53 UTC, kodumbeats commented
As of 631ecfd
```
$ docker-compose exec tests vendor/bin/phpunit --debug tests/Database/QueryTest.php
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Test 'Utopia\Tests\QueryTest::testParse' started
Test 'Utopia\Tests\QueryTest::testParse' ended
Test 'Utopia\Tests\QueryTest::testGetAttribute' started
Test 'Utopia\Tests\QueryTest::testGetAttribute' ended
Test 'Utopia\Tests\QueryTest::testGetOperator' started
Test 'Utopia\Tests\QueryTest::testGetOperator' ended
Test 'Utopia\Tests\QueryTest::testGetValue' started
Test 'Utopia\Tests\QueryTest::testGetValue' ended
Test 'Utopia\Tests\QueryTest::testGetQuery' started
Test 'Utopia\Tests\QueryTest::testGetQuery' ended


Time: 00:00.002, Memory: 6.00 MB

OK (5 tests, 22 assertions)
```

2021-04-26 16:23 UTC, eldadfux commented
Looks good! I would have added more tests to make sure casting works as expected with all types

2021-04-26 19:02 UTC, eldadfux requested changes

2021-04-26 19:02 UTC, eldadfux commented on src/Database/Query.php
> +                return str_replace(['"',"'"], "", $value);
We need to remove only the first and last chars if they are `"` or `'`

2021-04-26 19:02 UTC, eldadfux commented on src/Database/Query.php
> +        $values = array_map('trim', explode(',', $value));
Instead of using array map twice, we can have this trim as part of casting run - it will be more effective

2021-04-26 19:02 UTC, eldadfux commented on src/Database/Query.php
> +                return str_replace(['"',"'"], "", $value);
Maybe we should also handle escaping of `\'` and `\"`

2021-04-26 19:53 UTC, kodumbeats commented on src/Database/Query.php
> +            } elseif ($value === 'null') {
Removed one of these 👍🏻

2021-04-26 19:53 UTC, kodumbeats commented on src/Database/Query.php
> +                return str_replace(['"',"'"], "", $value);
Used `trim()` and `stripslashes()` for this

2021-04-26 19:53 UTC, kodumbeats commented on src/Database/Query.php
> +        $values = array_map('trim', explode(',', $value));
Agreed! 👍🏻

2021-04-26 20:13 UTC, TorstenDittmann commented on src/Database/Query.php
> +                // need special case to handle null with or without quotes
Is there even a need to handle a the case with a quoted `null`? 

imo it should be handled like a string then 🙂

2021-04-26 20:13 UTC, TorstenDittmann commented on src/Database/Query.php
> +        $end = mb_strpos($expression, ')');
Maybe consider using `mb_strrpos()` - notice the second `r`.
This way we ignore `)` as a part of the value.
https://www.php.net/manual/en/function.mb-strrpos.php

2021-04-26 21:27 UTC, eldadfux requested changes

2021-04-26 21:27 UTC, eldadfux commented on tests/Database/QueryTest.php
> +        $this->assertContains('Johnny Depp', $query->getValues());
I would expect ` Johnny Depp ` here. (with all the spaces)

2021-04-26 21:27 UTC, eldadfux commented on tests/Database/QueryTest.php
> +        $this->assertContains('Johnny Depp', $query->getValues());
we should only trim spaces around the quotes not within.

2021-04-26 21:46 UTC, merged