Allow for creation of collection with complete schema
utopia-php/database pull request #30
Opened 2021-06-28 21:21 UTC by kodumbeats

Creating collections with many attributes (for example, on startup of Appwrite, for testing) can be slow, so this PR adds additional params to `createCollection` to generate a complete collection with one call:
```php
abstract public function createCollection(string $name, array $attributes = [], array $indexes = []): bool;
```

**Testing**
Additional unit tests will be added to validate functionality.

2021-06-29 20:48 UTC, kodumbeats commented
I'm not 💯 convinced that Mongo is working properly, still need some more testing around it.

2021-07-01 03:37 UTC, eldadfux requested changes

2021-07-01 03:37 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +    public function getTypeForReadPermission(): string
```suggestion
    public function getTypeForReadPermission(): string
```

This should be a protected method used internally only by this class.

2021-07-01 03:37 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +    public function getIndexTypeForReadPermission(): string
This should be a protected method used internally only by this class.

2021-07-03 16:49 UTC, merged