Fix crud operations permission in update relationships
utopia-php/database pull request #300
Opened 2023-07-31 20:13 UTC by fanatic75

- Skipping authorization for crud operations which are integral parts of logic but not done by the user
- Fixes the bug in comparison of the old document and new document in the updateDocument function. 
- Added a test case.

2023-08-02 00:27 UTC, stnguyen90 requested changes

2023-08-02 00:27 UTC, stnguyen90 commented on src/Database/Database.php
> +                                $related = Authorization::skip(fn () => $this->getDocument($relatedCollection->getId(), $value));
What if the user doesn't have read access to the related document? 🧐

2023-08-02 03:22 UTC, fanatic75 commented on src/Database/Database.php
> +                                $related = Authorization::skip(fn () => $this->getDocument($relatedCollection->getId(), $value));
Why should the user have read access? The user is only performing an update operation. 

For eg ,
If a user has update permission on collection B,  
On a relationship A > B, and they are updating B via A, they should still be able to update B without having read permission on it.

2023-08-02 06:36 UTC, fanatic75 commented on src/Database/Database.php
> +        });
Yes, this has been fixed. It came due to merging a branch.

2023-08-09 02:41 UTC, abnegate commented on src/Database/Database.php
> +                                $related = Authorization::skip(fn () => $this->getDocument($relatedCollection->getId(), $value));
Now that we are setting the related document to null here if it does not exist or they don't have permission, we need to make sure auth is enabled here, so that when they read it, they still get null instead of an empty document

2023-08-17 21:22 UTC, stnguyen90 reviewed
Is this ready for review? Also, it looks like there are merge conflicts.

2023-08-18 15:02 UTC, abnegate commented
Closing as for now we don't want to allow relating to documents without read permission

2023-08-18 16:01 UTC, fanatic75 commented
@abnegate  
I have removed the ability to skip authentication when fetching related documents. However, we still need to perform certain operations, such as updating removed documents from the relation without authentication. 

Let's consider this scenario: Level 1 has a one-to-many relationship with Level 2. If we create new documents in Level 2 using Level 1, we should not need update permission in Level 2. However, due to updating old documents, we are unable to create new documents without update permission. This pull request resolves this issue.

2023-08-21 17:46 UTC, abnegate commented on src/Database/Database.php
> +                                        $this->skipRelationships(fn () => $this->updateDocument(
Can you explain this a bit more? Why does having the relationships populated here fail the comparison check?

2023-08-21 17:59 UTC, abnegate commented on tests/Database/Base.php
> +        $this->assertEquals(2, \count($updatedParent['children']));
This test would pass without the changes since we are only adding an item to the relationship, let's add a case where we remove an item from the relationship as well

2023-08-21 18:51 UTC, fanatic75 commented on src/Database/Database.php
> +                                        $this->skipRelationships(fn () => $this->updateDocument(
When updating the document with a two-way key, it's important to note that the key will not appear in the child document when the old version of the document is fetched. The key is simply used for the parent document to reference the child document.

2023-08-21 19:06 UTC, fanatic75 commented on src/Database/Database.php
> +                                        $this->skipRelationships(fn () => $this->updateDocument(
I have removed this for now.

2023-08-21 19:10 UTC, abnegate approved these changes

2023-08-21 19:20 UTC, stnguyen90 approved these changes

2023-08-21 21:20 UTC, merged