Feat isolation mode
utopia-php/database pull request #358
Opened 2023-11-17 01:43 UTC by abnegate

Allow setting different isolation modes by using different setters

Schema per project:
```php
$database
    ->setDatabase($projectId)
    ->create();
```

Single schema, unique tables (current arch):
```php
$database
    ->setDatabase('appwrite')
    ->setNamespace($projectId)
    ->create();
```

Single schema, shared tables:
```php
$database
    ->setDatabase('appwrite')
    ->setShareTables(true)
    ->setTenant($projectId)
    ->create();
```

2023-11-22 15:27 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +				`_tenant` VARCHAR(36) DEFAULT NULL,
If shareTables is false, do we want to create this attribute? can a shared table become a non-shared and the other way around? 
If we do not use _tenant , I am not sure we want to create

2023-11-22 15:28 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +				`_tenant` VARCHAR(36) DEFAULT NULL,
If _tenant will be the project Internal id in Appwrite , can it be an integer? I know it is less generic but better for us

2023-11-22 15:48 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +				KEY `_tenant` (`_tenant`),
Same question again about shareTables , if shareTables = true, it will always be added to the filter,
So could be we need to create the indexes with an if case.
For example if shareTables = false , We do not need this index:
KEY `_tenant` (`_tenant`)
and we will not create compound indexes as 
KEY `_created_at` (`_tenant`,`_createdAt`)

2023-11-22 15:56 UTC, fogelito commented on src/Database/Database.php
> +
If sharedTables is True , Do we want the add Tenant as first part of the index?

2023-11-22 17:31 UTC, fogelito commented on src/Database/Database.php
> +    public function setShareTables(bool $share): self
In case of $share = true, should we force to $tenant as a second function param?
So we do not need to check in functions this:
 if ($this->adapter->getShareTables() && empty($this->adapter->getTenant()))

2023-11-22 17:35 UTC, fogelito commented on src/Database/Database.php
> +        $this->adapter->setTenant($tenant);
Can we set setTenant while shared if false?

2023-11-23 23:46 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +				`_tenant` VARCHAR(36) DEFAULT NULL,
It could be anything, I have been using $project->getId(), but could certainly use internal ID since it's not exposed on the Appwrite side, that will much better for query performance, will update :+1:

2023-11-23 23:46 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +				`_tenant` VARCHAR(36) DEFAULT NULL,
We are just adding it to all tables to keep things simple, shouldn't be much impact if it's just unused right?

2023-11-23 23:49 UTC, abnegate commented on src/Database/Database.php
> +    public function setShareTables(bool $share): self
I think it's better to keep them separate, then from the Appwrite side, we only need to call setShareTables once when instantiating the DB, and then for every request, we call setTenant with the project ID

2023-11-23 23:49 UTC, abnegate commented on src/Database/Database.php
> +        $this->adapter->setTenant($tenant);
Yep, it will just not do anything

2023-11-24 01:15 UTC, eldadfux commented on src/Database/Database.php
> +        if ($this->adapter->getShareTables() && $collection->getAttribute('$tenant') !== $this->adapter->getTenant()) {
This could be another indication why having only tenant can be sufficient.

2023-11-24 01:15 UTC, eldadfux commented on src/Database/Database.php
> +        $this->deleteCachedDocument($collection->getId(), $id);
Calling this purgeDocument might help us have better separation and avoid confusion with the delete methods.

2023-11-24 01:15 UTC, eldadfux commented on src/Database/Adapter/SQL.php
> +			SELECT {$this->getAttributeProjection($selections)}
Indentation is off.

2023-11-24 01:15 UTC, eldadfux commented on src/Database/Adapter/SQL.php
> +        return 5;
Is there any way for us to count this? Can we use the attributes constant?

2023-11-24 01:15 UTC, eldadfux commented on src/Database/Adapter/SQL.php
> +        return 6;
Is there any way for us to count this? Can we use the attributes constant?

2023-11-24 01:15 UTC, eldadfux commented on src/Database/Adapter/SQL.php
> +                    $total += match (true) {
Cool, but let's keep the comments.

2023-11-24 01:15 UTC, eldadfux commented on src/Database/Adapter/Mongo.php
> +        return 6;
Is there any way for us to count this? Can we use the attributes constant?

2023-11-24 01:15 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +				KEY `_tenant` (`_tenant`),
I think we can always keep the index for simplicity and just set the tenant value to something default if not used.

2023-11-24 01:33 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +				KEY `_tenant` (`_tenant`),
@fogelito What would the impact on performance be if querying on only `_createdAt` (for existing projects)? The DB will still use the composite index even though it only matches one column, right?

Wondering about which order we should use as well because `(_tenant,_createdAt)` will perform much better for shared tables since tenant will massively reduce the rows, but `(_createdAt,_tenant)` would be much better for not-shared tables since tenant will always be null. 

Maybe it is worth conditionally creating them depending on whether shared tables is set or not

2023-11-24 03:55 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +				KEY `_tenant` (`_tenant`),
Changed this so we conditionally create the indexes optimized for performance

2023-11-24 03:55 UTC, abnegate commented on src/Database/Database.php
> +
Done

2023-11-24 04:29 UTC, abnegate commented on src/Database/Adapter.php
> +    public function setShareTables(bool $shareTables): bool
If we assume that, we also have to assume if it's not set, we're not using shared tables, which might not be the case (and will allow access to other tenants' data)

2023-11-24 04:38 UTC, abnegate commented on src/Database/Adapter/SQL.php
> +			SELECT {$this->getAttributeProjection($selections)}
Tabs vs spaces 😄

2023-11-26 19:17 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +				UNIQUE KEY _uid_tenant (_tenant, _uid),
Since _uid is much less in numbers than _tenant , and we have _tenant index in first position let's make this index 
UNIQUE KEY _uid_tenant (_uid, _tenant).

2023-11-26 19:19 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +				KEY _created_at (_tenant, _createdAt),
Do we have Workers / Maintance that can fetch data by _createdAt for example?
From a glance I tool in the Workers it always go by projected, we need to double check...

2023-11-26 19:44 UTC, fogelito commented on tests/e2e/Adapter/Base.php
> +        $this->assertEquals('Spiderman', $doc['name']);
Can we add an assertion that of $tenant (fetched) ===  $tenant1?

2023-11-27 01:43 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +				UNIQUE KEY _uid_tenant (_tenant, _uid),
Makes sense, will update :+1:

2023-11-27 01:44 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +				KEY _created_at (_tenant, _createdAt),
Everything must be by project ID, since there was no other option previously (everything is in either project or console namespace)

2023-11-27 01:48 UTC, abnegate commented on tests/e2e/Adapter/Base.php
> +        $this->assertEquals('Spiderman', $doc['name']);
Yep done

2023-11-27 10:58 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +					INDEX _permission (_permission, _type, _document, _tenant)
Hmm this Index supposed to cover :
SELECT _document
FROM `sharedTables`.`_people_perms`
WHERE _permission IN ('user:a', 'any', 'label:reader')
AND _type = 'read'
AND _tenant = :_tenant

INDEX _permission (_tenant, _type, _permission) 
We do not need _document in this Index, since we do not care about order by.

2023-11-27 11:36 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +					INDEX _permission (_permission, _type, _document, _tenant)
Updated 👌

2023-11-27 11:36 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +					INDEX _permission (_permission, _type, _document)
Done

2023-11-28 05:33 UTC, christyjacob4 commented
Let's setup a test bench to simulate the kind of loads we receive on cloud.

2023-11-28 20:30 UTC, fanatic75 commented on src/Database/Adapter/MariaDB.php
> +					INDEX _permission (_tenant, _permission, _type)
I think the correct order is _permission, _type only.

2023-11-28 21:19 UTC, fanatic75 requested changes

2023-11-28 21:19 UTC, fanatic75 commented on src/Database/Adapter/MariaDB.php
> +            $sql = "
I think the remove query and insert query should run in a single transaction, this can cause problems.

2023-11-29 06:58 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +					INDEX _permission (_tenant, _permission, _type)
We are not filtering or order by _document so we do not need it.

2023-11-29 07:02 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +					INDEX _permission (_tenant, _permission, _type)
We covers this query: 
SELECT `table_main`.*
            FROM `sharedTables`.`_people` as table_main
            WHERE table_main._uid IN (
                    SELECT _document
                    FROM `sharedTables`.`_people_perms`
                    WHERE _permission IN ('user:a', 'any', 'label:reader')
                      AND _type = 'read'
                      AND _tenant = :_tenant
                ) AND table_main._tenant = :_tenant
            ORDER BY table_main._id ASC
            LIMIT :limit OFFSET :offset;

2023-11-29 07:03 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +					INDEX _permission (_permission, _type)
We are not filtering or order by _document so we do not need it.

2023-11-29 09:31 UTC, fogelito commented on src/Database/Database.php
> +
On fulltext index we can't add _tenant

2023-11-29 12:38 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +				UNIQUE KEY _uid_tenant (_uid, _tenant),
We need to benchmark: do we need  an index (_tenant, _id) for find queries
 with no filters as `select * from table where _tenant  = 1 order by _id` 
 Or does_created_at index can cover it since (_tenant) is in the first position in Index tree 🤔

2023-11-29 12:40 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +				UNIQUE KEY _uid_tenant (_uid, _tenant),
@abnegate Perhaps we can add it, It will be easier to drop than create it later on..

2023-11-30 03:37 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +					INDEX _permission (_tenant, _permission, _type)
I agree here, _permission will make the traversal shorter than _type in this position right @fogelito?

2023-11-30 03:42 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +                $permissions[] = "('{$type}', '{$permission}', '{$document->getId()}', :_tenant)";
It's better to bind here, otherwise, we'll insert an empty string when `$this-tenant` is null

2023-11-30 03:42 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +        $attributes['_tenant'] = $this->tenant;
It will be inserted as `null`

2023-11-30 03:45 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +            $sql = "
All 3 (update data, remove permission, insert permissions) are executed in a transaction [later on](https://github.com/utopia-php/database/blob/main/src/Database/Adapter/MariaDB.php#L1038-L1049), we are just building the queries here

2023-11-30 03:53 UTC, abnegate commented on src/Database/Database.php
> +
Fixed and added test case :+1:

2023-11-30 08:26 UTC, fogelito commented on src/Database/Adapter/MariaDB.php
> +					INDEX _permission (_tenant, _permission, _type)
On this 
SELECT _document from PERMS
WHERE 
_permission IN ('user:a', 'any', 'label:reader') 
AND _type = 'read' 
AND _tenant = :_tenant;

So the MySQL engine will do this:
SELECT _document PERMS
WHERE _permission = 'user:a' AND _type = 'read' AND _tenant = :_tenant

SELECT _document PERMS
WHERE _permission = 'any' AND _type = 'read'  AND _tenant = :_tenant

SELECT _document PERMS
WHERE _permission ='label:reader'AND _type = 'read'  AND _tenant = :_tenant

So the question is what he will like better from the 3 options
If _permission would be a specific user as 'user:a' , he would like _permission first , but if _permission will be 'any' which has a lot of rows, So I would say last. 
So (without a benchmark is hard to know)

because we have Equal operation on _tenant, _type , that Is why I put them first,
What do you think?

2023-12-08 13:24 UTC, fogelito approved these changes

2023-12-08 16:02 UTC, merged