Change findFirst default limit to 1
utopia-php/database pull request #39
Opened 2021-07-20 14:43 UTC by kodumbeats

`Utopia\Database\Database->findFirst()` is primarily used to find a single document, so set the default limit to 1. 

A couple of observations.

- Thought about changing the default limit of `findLast` to 1 as well, but that change will make it exactly functional to `findFirst()`
- I couldn't find a single reference to the `findLast` method, is it necessary? 
- A more appropriate name for `findFirst()` based on our patterns might be `findOne()`, similar to other document-based DBMS ([ref: mongo](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-findOne/))

2021-07-20 14:56 UTC, eldadfux requested changes

2021-07-20 14:56 UTC, eldadfux commented on src/Database/Database.php
> +    public function findFirst(string $collection, array $queries = [], int $limit = 1, int $offset = 0, array $orderAttributes = [], array $orderTypes = [])
Actually I think we can completely remove it and just hardcode the number one when we call the `find` method.
Same should probably apply for `findLast`

2021-07-20 15:09 UTC, kodumbeats commented on src/Database/Database.php
> +    public function findFirst(string $collection, array $queries = [], int $limit = 1, int $offset = 0, array $orderAttributes = [], array $orderTypes = [])
I've updated this in 92107b8, though as written now, `findFirst()` and `findLast()` are functionally identical. I couldn't find any instances of calling `findLast()` - should we remove it?

2021-07-20 15:16 UTC, eldadfux commented
Maybe we can follow this nice convention and have one method named `findOne`?
https://docs.mongodb.com/manual/reference/method/db.collection.findOne/

2021-07-20 15:17 UTC, eldadfux commented on src/Database/Database.php
> +    public function findFirst(string $collection, array $queries = [], int $limit = 1, int $offset = 0, array $orderAttributes = [], array $orderTypes = [])
Maybe we can follow this nice convention and have one method named `findOne`?
https://docs.mongodb.com/manual/reference/method/db.collection.findOne/

2021-07-22 03:42 UTC, eldadfux approved these changes

2021-07-22 03:43 UTC, merged