feat(find): after document pagination
utopia-php/database pull request #40
Opened 2021-07-21 17:40 UTC by TorstenDittmann

- allow queries to paginate after a specific document
- for MariaDB, we are using the internal `_id` as a subsequent value to query after a certain document while allowing to sort
- since we need the internal `_id` and every attribute and its proper datatype, a document need to be passed instead of only its Document ID

References can be found here: https://shopify.engineering/pagination-relative-cursors

Todo:
- MongoDB

2021-07-22 04:06 UTC, eldadfux requested changes

2021-07-22 04:06 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +        if ($applyOrderAfter && is_null($orderAfter->getAttribute('_id', null))) {
With the new method this check might be redundant

2021-07-22 04:06 UTC, eldadfux commented on src/Database/Adapter/MariaDB.php
> +            $attribute = $orderAttributes[0];
Better use null safety operator to avoid any warnings

2021-07-22 07:18 UTC, TorstenDittmann commented on src/Database/Adapter/MariaDB.php
> +            $attribute = $orderAttributes[0];
Its null safe due to the check here https://github.com/utopia-php/database/blob/be48f14e413e6f3a807e0d5189e2a6cd9cbbda6e/src/Database/Adapter/MariaDB.php#L501

2021-07-22 07:18 UTC, TorstenDittmann commented on src/Database/Adapter/MariaDB.php
> +    public function getDocument(string $collection, string $id, bool $includeInternals = false): Document
Okay 👍

2021-07-22 07:55 UTC, TorstenDittmann commented on src/Database/Adapter/MariaDB.php
> +    public function getDocument(string $collection, string $id, bool $includeInternals = false): Document
Done.

2021-07-22 08:00 UTC, TorstenDittmann commented
According to the reviews I fixed the workflow. Fetching the `orderAfter` document will now be happening automatically, if the param is passed a document id.

That way its cleaner in the controllers.

2021-07-24 18:12 UTC, eldadfux requested changes

2021-07-24 18:12 UTC, eldadfux commented on src/Database/Adapter.php
> +    abstract public function getInternalId(Document $document);
I think we should completely avoid this method because it forces us to send another query to the database, and also move some business logic to the adapter where we would like to have on the main DB class. This design allow us to make the creation of new adapter as simple as possible if possible.

Instead I would just make sure that the original getDocument methods from the adapter will map `_id` to `$internalId` and return it with document. No need to expose `$internalId` in any response.

2021-07-24 18:12 UTC, eldadfux commented on src/Database/Adapter/MongoDB.php
> +        $uid = $collection->createIndex(['_uid' => $this->getOrder(Database::ORDER_DESC)], ['name' => '_uid', 'unique' => true]);
Isn't _uid our primary key already? @kodumbeats

2021-07-24 18:12 UTC, eldadfux commented on src/Database/Adapter/MongoDB.php
> +        if (empty($orderAttributes) && !empty($orderAfter)) {
I would love to discuss this section more in detail.

2021-07-24 18:12 UTC, eldadfux commented on src/Database/Database.php
> +    public function find(string $collection, array $queries = [], int $limit = 25, int $offset = 0, array $orderAttributes = [], array $orderTypes = [], string $orderAfter = null): array
It would be hard to return a proper error to the HTTP response. We can either pass a document instance and validate it in the controller before we pass it here, or we can throw a custom exception and make sure we catch it in the relevant route and delegate a proper HTTP error.

2021-07-24 18:12 UTC, eldadfux commented on src/Database/Document.php
> +    }
If we end up using this as a first class citizen attribute maybe we can drop the dedicated `set` method for it.

2021-07-24 18:12 UTC, eldadfux commented on src/Database/Document.php
> +            if(array_key_exists($attribute, ['$id' => true, '$internalId' => true, '$collection' => true, '$read' => true, '$write' => []])) {
👌

2021-07-24 18:12 UTC, eldadfux commented on tests/Database/Adapter/MongoDBTest.php
> +    static function getUsedIndexes(): int
Not sure how we use this methods in the test suite is this part of another PR?

2021-07-24 18:25 UTC, TorstenDittmann commented on src/Database/Adapter/MongoDB.php
> +        if (empty($orderAttributes) && !empty($orderAfter)) {
The query for after pagination depends on what the first order attribute is. If there is no order attribute - we need to add a special case to make after pagination working 👍🏻

2021-07-26 07:19 UTC, TorstenDittmann commented on src/Database/Adapter/MongoDB.php
> +        $uid = $collection->createIndex(['_uid' => $this->getOrder(Database::ORDER_DESC)], ['name' => '_uid', 'unique' => true]);
We have overwritten the automatic `_id` from mongo with ours. But we need to take advantage of the auto generated `_id` by MongoDB now for pagination 👍🏻 

Thats why I added the `_uid` attribute.

2021-07-26 07:22 UTC, TorstenDittmann commented on tests/Database/Adapter/MongoDBTest.php
> +    static function getUsedIndexes(): int
We are testing the maximum number of indexes in the tests. Previously all Adapters had the same amount of used indexes by default. Now with MongoDB we added another index and we need to tell the tests how many indexes are used by default 👍🏻

2021-07-26 07:51 UTC, TorstenDittmann commented on src/Database/Database.php
> +    public function find(string $collection, array $queries = [], int $limit = 25, int $offset = 0, array $orderAttributes = [], array $orderTypes = [], string $orderAfter = null): array
Fixed 👍🏻

2021-07-26 07:51 UTC, TorstenDittmann commented on src/Database/Document.php
> +    }
Fixed 👍🏻

2021-07-26 07:51 UTC, TorstenDittmann commented on src/Database/Adapter.php
> +    abstract public function getInternalId(Document $document);
Fixed 👍🏻

2021-07-28 21:02 UTC, kodumbeats requested changes
Do we have any performance data behind this new pagination? I see OR statements in both the SQL and Mongo adapters, so I just want to understand the tradeoff we're making (since `after` pagination scales much better)

2021-07-28 21:19 UTC, TorstenDittmann commented on src/Database/Adapter/MongoDB.php
> +        if (!$read || !$write || $uid) {
Good catch!

2021-07-28 21:20 UTC, TorstenDittmann commented
> Do we have any performance data behind this new pagination? I see OR statements in both the SQL and Mongo adapters, so I just want to understand the tradeoff we're making (since `after` pagination scales much better)

The initial benchmark I did was very much what you can find here: https://shopify.engineering/pagination-relative-cursors

2021-08-04 16:42 UTC, kodumbeats approved these changes

2021-08-04 16:53 UTC, merged