Remove DROP TABLE IF EXISTS
utopia-php/database pull request #489
Opened 2024-12-01 07:48 UTC by fogelito

2024-12-01 07:50 UTC, stnguyen90 requested changes
Lint error

2024-12-01 07:54 UTC, stnguyen90 approved these changes

2024-12-02 01:18 UTC, abnegate commented on src/Database/Adapter/MariaDB.php
> +            //            }
```suggestion
```

2024-12-02 01:19 UTC, abnegate reviewed
This should never happen unless `getCollection` incorrectly returns an empty document in the `Database` wrapping method :thinking: maybe because of replication lag?

2024-12-02 01:59 UTC, merged