Add query validator
utopia-php/database pull request #5
Opened 2021-04-28 22:10 UTC by kodumbeats

This PR introduces a query validator which checks a query against a collection schema for validity.

2021-04-28 22:13 UTC, kodumbeats commented
As of ea0c622
```bash
$ docker-compose exec tests vendor/bin/phpunit --debug tests/Database/Validator/QueryValidatorTest.php
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Test 'Utopia\Tests\Validator\QueryValidatorTest::testQuery' started
Test 'Utopia\Tests\Validator\QueryValidatorTest::testQuery' ended
Test 'Utopia\Tests\Validator\QueryValidatorTest::testInvalidOperator' started
Test 'Utopia\Tests\Validator\QueryValidatorTest::testInvalidOperator' ended
Test 'Utopia\Tests\Validator\QueryValidatorTest::testAttributeNotFound' started
Test 'Utopia\Tests\Validator\QueryValidatorTest::testAttributeNotFound' ended
Test 'Utopia\Tests\Validator\QueryValidatorTest::testAttributeWrongType' started
Test 'Utopia\Tests\Validator\QueryValidatorTest::testAttributeWrongType' ended


Time: 00:00.003, Memory: 6.00 MB

OK (4 tests, 7 assertions)

$ docker-compose exec tests vendor/bin/phpunit --debug tests/Database/Adapter/MariaDBTest.php
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDelete' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDelete' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDeleteCollection' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDeleteCollection' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDeleteAttribute' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDeleteAttribute' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDeleteIndex' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDeleteIndex' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDocument' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testCreateDocument' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testGetDocument' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testGetDocument' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testUpdateDocument' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testUpdateDocument' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testDeleteDocument' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testDeleteDocument' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testFindFirst' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testFindFirst' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testFindLast' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testFindLast' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testReadPermissionsSuccess' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testReadPermissionsSuccess' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testReadPermissionsFailure' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testReadPermissionsFailure' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testWritePermissionsSuccess' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testWritePermissionsSuccess' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testWritePermissionsFailure' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testWritePermissionsFailure' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testWritePermissionsUpdateFailure' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testWritePermissionsUpdateFailure' ended
Test 'Utopia\Tests\Adapter\MariaDBTest::testExceptionDuplicate' started
Test 'Utopia\Tests\Adapter\MariaDBTest::testExceptionDuplicate' ended


Time: 00:00.752, Memory: 6.00 MB

OK (16 tests, 94 assertions)
```

2021-04-29 12:02 UTC, eldadfux requested changes

2021-04-29 12:02 UTC, eldadfux commented on tests/Database/Validator/QueryValidatorTest.php
> +        $validator->isValid(Query::parse('title.eqqual("Iron Man")'));
You can also add an assertion for false here.

2021-04-29 12:02 UTC, eldadfux commented on tests/Database/Validator/QueryValidatorTest.php
> +        $validator->isValid(Query::parse('name.equal("Iron Man")'));
You can also add an assertion for false here.

2021-04-29 12:02 UTC, eldadfux commented on tests/Database/Validator/QueryValidatorTest.php
> +        $validator->isValid($query);
You can also add an assertion for false here.

2021-04-29 15:12 UTC, eldadfux commented on src/Database/Database.php
> +    const VAR_FLOAT = 'double';
Why did we make this change?

2021-04-29 15:18 UTC, kodumbeats commented on src/Database/Database.php
> +    const VAR_FLOAT = 'double';
This change allows me to use `gettype()` to check query types like so:

https://github.com/utopia-php/database/pull/5/files#diff-ac45b4d47a0dc7e4cbe156eba6050dfee59d5ef191cda5d0096db64f512bd1c5R89

From the docs:
>  "double" (for historical reasons "double" is returned in case of a float, and not simply "float")

2021-04-29 17:08 UTC, merged