get sum and related tests
utopia-php/database pull request #60
Opened 2021-08-17 08:21 UTC by lohanidamodar

Adds new method to get sum of an attribute

2021-08-17 17:07 UTC, kodumbeats requested changes
:)

2021-08-17 17:07 UTC, kodumbeats commented on tests/Database/Base.php
> +    public function testSum()
Can we also test the `$max` param?

2021-08-17 17:07 UTC, kodumbeats commented on src/Database/Database.php
> +        $count = $this->adapter->sum($collection, $attribute, $queries, $max);
If we're enforcing a `$max` limit, do we also need to worry about orders/offsets when calling `sum()`?

2021-08-17 17:07 UTC, kodumbeats commented on src/Database/Adapter/MongoDB.php
> +        return ($collection->aggregate($pipeline, $options)->toArray()[0] ?? [])['total'] ?? 0;
Can we get some documentation here? After `$collection->aggregate()`, I'm not sure what's going on.

2021-08-18 05:44 UTC, lohanidamodar commented on src/Database/Adapter/MongoDB.php
> +        return ($collection->aggregate($pipeline, $options)->toArray()[0] ?? [])['total'] ?? 0;
Not even me, it took quite a bit of Google search for both @TorstenDittmann and met to get this working. 

Will add what I understood.

2021-08-18 05:46 UTC, lohanidamodar commented on src/Database/Database.php
> +        $count = $this->adapter->sum($collection, $attribute, $queries, $max);
@kodumbeats I'm not sure either, I basically replicated `count` method, and only changed the SQL query to get the `sum`. So It should work exactly as `count` works with `$max`, WDYT?

2021-08-18 05:46 UTC, lohanidamodar commented on tests/Database/Base.php
> +    public function testSum()
sure

2021-08-18 05:48 UTC, lohanidamodar commented on src/Database/Adapter.php
> +     * Sum an attribute
It was my mistake.

2021-08-18 06:06 UTC, eldadfux approved these changes
Nothing to add on top of @kodumbeats comments.

2021-08-18 06:38 UTC, lohanidamodar commented on src/Database/Adapter/MongoDB.php
> +        return ($collection->aggregate($pipeline, $options)->toArray()[0] ?? [])['total'] ?? 0;
Updated with comments

2021-08-18 06:38 UTC, lohanidamodar commented
> Nothing to add on top of @kodumbeats comments.

Fixed, mongodb sum and updated the tests and comments as requested.

2021-08-18 07:05 UTC, eldadfux requested changes

2021-08-18 07:05 UTC, eldadfux commented on tests/Database/Base.php
> +        $count = static::getDatabase()->sum('movies', 'year', [new Query('year', Query::TYPE_EQUAL, [2019])], 1);
```suggestion
        $sum = static::getDatabase()->sum('movies', 'year', [new Query('year', Query::TYPE_EQUAL, [2019])], 1);
```

2021-08-18 07:05 UTC, eldadfux commented on tests/Database/Base.php
> +        $this->assertEquals(2019, $count);
```suggestion
        $this->assertEquals(2019, $sum);
```

2021-08-18 07:17 UTC, lohanidamodar commented
@eldadfux updated fixed the naming issue in the tests

2021-08-18 07:34 UTC, eldadfux approved these changes

2021-08-18 12:10 UTC, kodumbeats commented on src/Database/Database.php
> +        $count = $this->adapter->sum($collection, $attribute, $queries, $max);
Fair enough - if we need that functionality, we can add it later 👍🏻

2021-08-18 12:13 UTC, kodumbeats approved these changes

2021-08-18 12:16 UTC, merged