Allow filters on null values
utopia-php/database pull request #64
Opened 2021-08-20 11:16 UTC by eldadfux

2021-08-20 19:10 UTC, kodumbeats requested changes

2021-08-20 19:10 UTC, kodumbeats commented on src/Database/Database.php
> +    protected function decodeAttribute(string $name, $value, Document $document, Document $collection)
Now that we've extended this method to allow us to aggregate&cache the `$collection` document, I think this method could use some additional documentation. Without the Appwrite context, I wouldn't know why we're passing the collection and document.

2021-08-20 19:10 UTC, kodumbeats commented on src/Database/Database.php
> +
```suggestion
```

2021-08-21 09:51 UTC, eldadfux commented on src/Database/Database.php
> +    protected function decodeAttribute(string $name, $value, Document $document, Document $collection)
Added a description in the doc-block. Removed the collection for now as we don't really use it at this stage.

2021-08-21 17:11 UTC, kodumbeats approved these changes
👍🏻

2021-08-22 12:50 UTC, merged