Feature - Strict Query Validation
utopia-php/database pull request #7
Opened 2021-04-30 21:33 UTC by kodumbeats

This PR introduces a new Queries validator to validate an array of Query objects by:
- Individually validating each Query object
- **Strict validation**: validate the query params can all be found in one index

Test plan:
Unit tests included

2021-05-01 05:21 UTC, eldadfux commented
@kodumbeats I might also add a new collection attributed called "indexesInQueue" to hold pending indexes that are still being created, this will allow us to give a better error messages in this validator.

2021-05-04 20:18 UTC, kodumbeats commented
@eldadfux I'm not 💯 on what is best to pass to the Queries validator constructor. I landed on this approach in acefb92 because passing in `Utopia\Database\Database` made the code really messy, and I lost the story.

2021-05-05 13:20 UTC, eldadfux requested changes
Looks very good, left some minor comments. When ready I can merge it and start playing around with it :)

2021-05-05 13:20 UTC, eldadfux commented on src/Database/Validator/Queries.php
> +                if ($index['attributes'] === $queries) {
I'm not sure this array comparison in PHP actually work

2021-05-05 13:20 UTC, eldadfux commented on src/Database/Validator/Queries.php
> +                        $queued = true;
If an index was found in the queue, we can stop the iteration by returning false. It will be faster.

2021-05-05 17:16 UTC, kodumbeats commented on src/Database/Validator/Queries.php
> +                if ($index['attributes'] === $queries) {
Moved array comparison logic to its own method. 👍🏻

2021-05-13 13:53 UTC, eldadfux approved these changes

2021-05-13 13:54 UTC, merged