Feat: MongoDB Adapter
utopia-php/database pull request #8
Opened 2021-05-06 21:39 UTC by kodumbeats

This PR adds a MongoDB database adapter

2021-05-06 21:46 UTC, kodumbeats commented
@eldadfux  I could use your advice going forward:

When fetching documents, Mongo client SDK returns everything in a `MongoDB\Model\BSONDocument` object:
https://docs.mongodb.com/php-library/v1.2/reference/bson/#phpclass.MongoDB\Model\BSONDocument

What'd be the best approach to parse these objects and get back the PHP array? I've found I can go one level deep with `iterator_to_array`, but the array contains BSON models as well (`MongoDB\Model\BSONArray` and `MongoDB\BSON\ObjectId`) - looks like this:

```php
array(10) {
  ["_id"]=>
  object(MongoDB\BSON\ObjectId)#167 (1) {
    ["oid"]=>
    string(24) "60945e59acf8b169f83ce597"
  }
  ["+id"]=>
  string(9) "documents"
  ["+read"]=>
  object(MongoDB\Model\BSONArray)#164 (1) {
    ["storage":"ArrayObject":private]=>
    array(1) {
      [0]=>
      string(1) "*"
    }
  }
  ["+write"]=>
  object(MongoDB\Model\BSONArray)#169 (1) {
    ["storage":"ArrayObject":private]=>
    array(1) {
      [0]=>
      string(1) "*"
    }
  }
  ["name"]=>
  string(9) "documents"
  ["attributes"]=>
  string(2) "[]"
  ["indexes"]=>
  string(2) "[]"
  ["attributesInQueue"]=>
  string(2) "[]"
  ["indexesInQueue"]=>
  string(2) "[]"
  ["+collection"]=>
  string(11) "collections"
}

```

2021-05-06 22:08 UTC, TorstenDittmann commented
> @eldadfux  I could use your advice going forward:
> 
> When fetching documents, Mongo client SDK returns everything in a `MongoDB\Model\BSONDocument` object:
> https://docs.mongodb.com/php-library/v1.2/reference/bson/#phpclass.MongoDB\Model\BSONDocument
> 
> What'd be the best approach to parse these objects and get back the PHP array? I've found I can go one level deep with `iterator_to_array`, but the array contains BSON models as well (`MongoDB\Model\BSONArray` and `MongoDB\BSON\ObjectId`) - looks like this:
> 
> ```php
> array(10) {
>   ["_id"]=>
>   object(MongoDB\BSON\ObjectId)#167 (1) {
>     ["oid"]=>
>     string(24) "60945e59acf8b169f83ce597"
>   }
>   ["+id"]=>
>   string(9) "documents"
>   ["+read"]=>
>   object(MongoDB\Model\BSONArray)#164 (1) {
>     ["storage":"ArrayObject":private]=>
>     array(1) {
>       [0]=>
>       string(1) "*"
>     }
>   }
>   ["+write"]=>
>   object(MongoDB\Model\BSONArray)#169 (1) {
>     ["storage":"ArrayObject":private]=>
>     array(1) {
>       [0]=>
>       string(1) "*"
>     }
>   }
>   ["name"]=>
>   string(9) "documents"
>   ["attributes"]=>
>   string(2) "[]"
>   ["indexes"]=>
>   string(2) "[]"
>   ["attributesInQueue"]=>
>   string(2) "[]"
>   ["indexesInQueue"]=>
>   string(2) "[]"
>   ["+collection"]=>
>   string(11) "collections"
> }
> 
> ```

https://stackoverflow.com/a/61972048

Did you try this?

2021-05-13 03:57 UTC, eldadfux requested changes

2021-05-13 03:57 UTC, eldadfux commented on src/Database/Database.php
>      {
A more readable way might be:

```php
if ($this->adapter->getSupportForCasting()) {
    return $document;
}
```

2021-05-13 14:35 UTC, kodumbeats commented on src/Database/Adapter/MongoDB.php
> +            $filters['+read']['$in'] = Authorization::getRoles();
Mongo creates a unique index on `_id` when creating a collection, so we have that by default. For `$read` and `$write`, should we create these indexes at the database level when creating a collection?
For example, [`Utopia\Database\Database->createCollection()`](https://github.com/utopia-php/database/blob/main/src/Database/Database.php#L259):

```php
if ($this->adapter->getSupportForIndex) {
    $this->adapter->createIndex(...);
}
```

2021-05-13 14:38 UTC, eldadfux commented on src/Database/Adapter/MongoDB.php
> +            $filters['+read']['$in'] = Authorization::getRoles();
I would keep them in the adapter for now, just because nosql vs sql behavior is very different for the way we handle permissions.

2021-05-13 21:29 UTC, eldadfux requested changes

2021-05-13 21:29 UTC, eldadfux commented on src/Database/Adapter/MongoDB.php
> +            $found[] = new Document($this->replaceChars('_', '$', $result));
I feel like `replaceChars` is very expensive. We can probably just replace `$id`, `$read`, and `$write`.

2021-05-13 21:29 UTC, eldadfux commented on src/Database/Adapter/MongoDB.php
> +        $options = ['sort', 'limit' => $limit, 'skip' => $offset];
```suggestion
        $options = ['sort' => [], 'limit' => $limit, 'skip' => $offset];
```

2021-05-13 21:29 UTC, eldadfux commented on src/Database/Adapter/MongoDB.php
> +        $options['limit'] = $max;
We need to make sure this limits the number of documents the DB scans and not just the number of results returned (which is always 1 anyway).

2021-05-13 21:29 UTC, eldadfux commented on src/Database/Adapter/MongoDB.php
> +    public function getSupportForCasting(): bool
```suggestion
    /**
     * Is casting supported?
     * 
     * @return bool
     */
    public function getSupportForCasting(): bool
```

2021-05-13 21:29 UTC, eldadfux commented on src/Database/Adapter/MongoDB.php
> +                case Database::INDEX_KEY:
Missing support for a unique index? don't we have a test for this?

2021-05-14 11:31 UTC, kodumbeats commented on src/Database/Adapter/MongoDB.php
> +                case Database::INDEX_KEY:
Happy to add unique indexes and tests, we don't have any right now:

https://github.com/utopia-php/database/blob/main/tests/Database/Base.php#L151-L177

2021-05-14 11:36 UTC, kodumbeats commented on src/Database/Adapter/MongoDB.php
> +        $options['limit'] = $max;
I'm not sure on this one:
According to the [mongo shell docs](https://docs.mongodb.com/manual/reference/method/db.collection.count/):

Field | Type | Description
-- | -- |  --
limit | integer | Optional. The maximum number of documents to count.

But for the [PHP lib](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-countDocuments/) implementation of the same method:
Field | Type | Description
-- | -- |  --
limit | integer | Optional. The maximum number of matching documents to return.

I think all implementations just limit the number of documents passed to the next step in the pipeline:
https://docs.mongodb.com/manual/reference/operator/aggregation/limit/

2021-05-14 11:38 UTC, eldadfux commented on src/Database/Adapter/MongoDB.php
> +        $options['limit'] = $max;
Maybe we can raise an issue on the Mongo SDK repo and ask. I feel like this is just a doc mistake

2021-05-14 11:38 UTC, eldadfux commented on src/Database/Adapter/MongoDB.php
> +                case Database::INDEX_KEY:
👌🏻

2021-05-14 15:02 UTC, kodumbeats commented on src/Database/Adapter/MongoDB.php
> +            $found[] = new Document($this->replaceChars('_', '$', $result));
Had to replace `$collection` as well:  ebf9c4c

2021-05-14 15:39 UTC, kodumbeats commented on src/Database/Adapter/MongoDB.php
> +                case Database::INDEX_KEY:
bbf2f3f

2021-05-14 16:33 UTC, kodumbeats commented on src/Database/Adapter/MongoDB.php
> +        $options['limit'] = $max;
Yep, `limit` was the wrong setting. After more research, I have good news and bad news 😐 

Good news: I found the exact setting we need for our desired `count()` and `find()` methods: `maxScan`:
> maxScan Optional. Maximum number of documents or index keys to scan when executing the query.

Bad news: it was deprecated in Mongo 4.0 in favor of time-based limits:
> MongoDB deprecates the option maxScan for the find command and the mongo shell helper cursor.maxScan(). Instead, use maxTimeMS option or the helper cursor.maxTimeMS().

https://docs.mongodb.com/manual/release-notes/4.0-compatibility/#maxscan-option

Since the behavior was specifically deprecated by the Mongo team, I'm not sure we'll be able to hack our way around it.

2021-05-17 13:28 UTC, merged