Feat-auth-improvement
utopia-php/database pull request #85
Opened 2021-11-17 07:35 UTC by lohanidamodar

Imrpving authorization to support database cloning and disabling auth only in particular instance

2021-11-17 13:56 UTC, eldadfux commented on src/Database/Database.php
> +    public function __clone()
I think this may overwrite the original clone behavior. Maybe we should add a call for __parent::_clone(); or something like that at the bottom?

2021-11-17 13:57 UTC, eldadfux commented
> Maybe I missed a conversation, but I thought we discussed cloning the entire Database object Appwrite-side and overwriting the Authorization validator so we can customize the Auth object for just a single request lifecycle. How does this refactor help us overwrite Auth behavior?

We also mentioned we can access the read and write auth object and just set them with `->disable()` instead of overwriting them as long as we don't affect the original instances, but only the cloned objects.

2021-11-17 14:06 UTC, lohanidamodar commented on src/Database/Database.php
> +    public function __clone()
https://www.php.net/manual/en/language.oop5.cloning.php
From here, the __clone method is called on newly cloned object once the clone is complete

2021-11-17 14:08 UTC, TorstenDittmann commented
Looking at this current implementation right now - I feel like we can achieve a more cleaner solution with not cloning the object at all.

What if we allow the constructor to be passed a Validator class - that we can then extend in Appwrite itself?

2021-11-17 14:10 UTC, lohanidamodar commented
> > Maybe I missed a conversation, but I thought we discussed cloning the entire Database object Appwrite-side and overwriting the Authorization validator so we can customize the Auth object for just a single request lifecycle. How does this refactor help us overwrite Auth behavior?
> 
> We also mentioned we can access the read and write auth object and just set them with `->disable()` instead of overwriting them as long as we don't affect the original instances, but only the cloned objects.

Based on your feedback here
https://discord.com/channels/564160730845151244/808657214708908032/910453704560345109
I went ahead to remove the static methods completely, in favor of using Skip where applicable and cloning and using the disable as I'm doing 
https://github.com/utopia-php/database/blob/e319d1d65ee9ed31a5e457ae14124a089be06278/tests/Database/Base.php#L1294

2021-11-18 11:51 UTC, TorstenDittmann commented on src/Database/Validator/Authorization.php
>      public static function skip(callable $callback)
Can we add the `mixed` return type here?

2021-11-18 11:51 UTC, TorstenDittmann commented on src/Database/Database.php
> +    }
Please add PHPDocs and return types 🙏🏻

2021-11-18 11:51 UTC, TorstenDittmann commented on src/Database/Database.php
> +    protected $write;
Is it possible to add the Class type to these variables?

2021-11-18 12:04 UTC, lohanidamodar commented on src/Database/Validator/Authorization.php
>      public static function skip(callable $callback)
adding mixed as return type for function, psalm throws error
![image](https://user-images.githubusercontent.com/6360216/142412047-8e4bc210-cdf7-4f9f-a0ee-212c2eae9a31.png)

2021-11-22 22:20 UTC, kodumbeats requested changes
Small merge conflict too, it seems.

2021-11-22 22:20 UTC, kodumbeats commented on src/Database/Database.php
> +    public function getRead(): Authorization
I don't think `$database->getRead()` tells the right story. Maybe:
```suggestion
    public function getReadValidator(): Authorization
```
I think we should be more verbose with these variables/methods, else the context gets lost.

2021-11-22 22:20 UTC, kodumbeats commented on src/Database/Validator/Authorization.php
> +    protected $authStatus = true;
Can we add a todo to replace this with an enum with PHP8.1? Without explanation, I couldn't tell you the difference between `$status`, `$authStatus`, or `$statusDefault`, and enums would help a _lot_.

2021-11-22 22:20 UTC, kodumbeats commented on src/Database/Validator/Authorization.php
>      public static function skip(callable $callback)
Maybe because the `mixed` type is a PHP8 feature? In PHP7, they'd be in [reserved status](https://wiki.php.net/rfc/reserve_even_more_types_in_php_7#result)

2021-11-23 05:00 UTC, lohanidamodar commented on src/Database/Validator/Authorization.php
> +    protected $authStatus = true;
I'm not happy with this name either, but I don't have other better name in mind. How will we name this even with enums any ideas what you are thinking ?

2021-11-23 05:01 UTC, lohanidamodar commented on src/Database/Validator/Authorization.php
>      public static function skip(callable $callback)
It should be, however we are in PHP 8 right, even then Pslam throws error.

2021-12-05 06:55 UTC, eldadfux commented on src/Database/Validator/Authorization.php
>      public static function skip(callable $callback)
Let's keep a TODO in the code and tackle this later.

2021-12-05 06:57 UTC, eldadfux commented on src/Database/Validator/Authorization.php
> +    protected $authStatus = true;
@lohanidamodar lets start by adding doc blocks descriptions, and than re-review the names of the vars. I totally agree at this state they make almost 0 sense.

2021-12-05 07:00 UTC, eldadfux commented
> Looking at this current implementation right now - I feel like we can achieve a more cleaner solution with not cloning the object at all.
> 
> What if we allow the constructor to be passed a Validator class - that we can then extend in Appwrite itself?

This solution is almost ready, and is pretty solid. I would suggest completing it for the upcoming release, and continue the discussion on other alternatives based on our availability after the scheduled release.

2021-12-07 10:08 UTC, TorstenDittmann commented on src/Database/Validator/Authorization.php
>      public static function skip(callable $callback)
Updating Psalm should fix this.

2021-12-10 18:53 UTC, kodumbeats approved these changes

2022-09-03 10:03 UTC, eldadfux commented
Closing for now due to too many changes done in Database permissions recently.

2022-09-03 10:03 UTC, closed without merging