Feat:  Adds the start of code coverage.
utopia-php/database pull request #88
Opened 2021-11-23 16:40 UTC by wess

Beginnings of adding code coverage to projects using PHPUnit. This uses PCOV as the driver and updates the phpunit.xml to include filters for coverage. 

required PCOV:
`$ pecl install pcov`

Then run:
`$ phpunit --coverage-text=tests/coverage/report.txt`

Adapters, in tests, are updated to allow for environment variables for connections, as well as the original as fallback.

2021-11-23 19:59 UTC, kodumbeats commented on tests/Database/Adapter/MariaDBTest.php
> +        $dbPort = getenv('MARIA_PORT') ?: '3307';
Ah, here it is. Tests are failing for MariaDB because it's available on port **3306** in the `docker-compose.yml` stack. I patched this locally, and then tests run 🟢 
https://github.com/utopia-php/database/blob/75f206d796dc1b839441fceca2d3dd0186a627a4/docker-compose.yml#L37-L45
```suggestion
        $dbPort = getenv('MARIA_PORT') ?: '3306';
```

2021-12-05 06:53 UTC, eldadfux reviewed
Is there a way to generate a code coverage badge for the repo with the total/average score?

2021-12-05 06:53 UTC, eldadfux commented on phpunit.xml.bak
> +<phpunit backupGlobals="false"
No need for the old version when this PR is good to go.

2021-12-10 00:05 UTC, christyjacob4 requested changes
Is there a reason we are using a dependency for generating a coverage report ? How would it be different from simply using the coverage report that `phpunit` provides out of the box ?

IMO it would be much cleaner to use 
`vendor/bin/phpunit --coverage-clover coverage.xml` and use the [Codecov service](https://github.com/codecov/example-php) that will take care of generating dynamic code coverage README badges and even provides some other features. 

cc: @eldadfux

2021-12-10 11:10 UTC, TorstenDittmann commented
> Is there a reason we are using a dependency for generating a coverage report ? How would it be different from simply using the coverage report that `phpunit` provides out of the box ?
> 
> IMO it would be much cleaner to use `vendor/bin/phpunit --coverage-clover coverage.xml` and use the [Codecov service](https://github.com/codecov/example-php) that will take care of generating dynamic code coverage README badges and even provides some other features.
> 
> cc: @eldadfux

Not sure I understand? That is the Code coverage that PHP offers out of the box 😄 

You need some kind of driver that can actually check what code is covered or not => https://phpunit.readthedocs.io/en/9.5/code-coverage-analysis.html

Even the official code cov example does not work because there is no driver for this installed:

![Bildschirmfoto 2021-12-10 um 12 10 28](https://user-images.githubusercontent.com/1759475/145565079-cf2aea8a-bc8e-4fc5-8495-2705d310420a.png)

2021-12-22 04:20 UTC, eldadfux commented
I think the dependency should be fine and as far as I can recall is required.

2021-12-22 04:21 UTC, eldadfux commented on tests/coverage/report.txt
> +
Is this a file of cached results? should we add it to gitignore or we need to have it for the results badge? Can we auto-generate it?

2023-01-10 05:09 UTC, abnegate reviewed
@wess I'd love to get this up to date! If you could address the conflicts and pending feedback we can push it along 😁

2023-02-13 08:55 UTC, closed without merging